SYSTEM     = x86-64_linux
LIBFORMAT  = static_pic

#------------------------------------------------------------
#
# When you adapt this makefile to compile your CPLEX programs
# please copy this makefile and set CPLEXDIR and CONCERTDIR to
# the directories where CPLEX and CONCERT are installed.
#
#------------------------------------------------------------

CPLEXDIR      = /home/bahar/opt/ibm/ILOG/CPLEX_Studio127/cplex
CONCERTDIR    = /home/bahar//opt/ibm/ILOG/CPLEX_Studio127/concert

# ---------------------------------------------------------------------
# Compiler selection 
# ---------------------------------------------------------------------

CC  = gcc -O0

# ---------------------------------------------------------------------
# Compiler options 
# ---------------------------------------------------------------------

COPT  = -m64 -fPIC -fno-strict-aliasing

# ---------------------------------------------------------------------
# Link options and libraries
# ---------------------------------------------------------------------

CPLEXBINDIR   = $(CPLEXDIR)/bin/$(BINDIST)
CPLEXLIBDIR   = $(CPLEXDIR)/lib/$(SYSTEM)/$(LIBFORMAT)
CONCERTLIBDIR = $(CONCERTDIR)/lib/$(SYSTEM)/$(LIBFORMAT)

CLNDIRS   = -L$(CPLEXLIBDIR) -L../src -L/home/bahar/instantclient -L/home/bahar/instantclient/ocilib
CLNFLAGS  = ../src/.libs/libsrc.a -lcplex -lm -lpthread /usr/lib/x86_64-linux-gnu/libsqlite3.so -lpq -lreadline -locilib -locci -lclntsh


all:
	make -f Makefile.cplex all_c

execute: all
	make execute_c

CONCERTINCDIR = $(CONCERTDIR)/include
CPLEXINCDIR   = $(CPLEXDIR)/include

CFLAGS  = $(COPT)  -I$(CPLEXINCDIR) -I../include -I.. -std=gnu99 


#------------------------------------------------------------
#  make all      : to compile the examples. 
#  make execute  : to compile and execute the examples.
#------------------------------------------------------------


C_EX = testexprtocp


all_c: $(C_EX)

execute_c: $(C_EX)
	 ./testexprtocp
	 
# ------------------------------------------------------------

clean :
	/bin/rm -rf *.o *~ *.class
	/bin/rm -rf $(C_EX)
	/bin/rm -rf *.mps *.ord *.sos *.lp *.sav *.net *.msg *.log *.clp

# ------------------------------------------------------------
#
# The examples
#
testexprtocp: test_expr_to_cplex.o
	$(CC) $(CFLAGS) $(CLNDIRS) -o testexprtocp test_expr_to_cplex.o $(CLNFLAGS)
test_expr_to_cplex.o: test_expr_to_cplex.c
	$(CC) -c $(CFLAGS) test_expr_to_cplex.c -o test_expr_to_cplex.o


# Local Variables:
# mode: makefile
# End:
