CREATE TABLE rtpcq03 AS
SELECT F1.L_ORDERKEY AS A0, F1.O_ORDERDATE AS A1, F1.O_SHIPPRIORITY AS A2, sum((F2.L_EXTENDEDPRICE * (CAST (1 AS DOUBLE) - F2.L_DISCOUNT))) AS A3
FROM (((
SELECT F0.C_CUSTKEY AS C_CUSTKEY, F0.C_NAME AS C1, F0.C_ADDRESS AS C2, F0.C_NATIONKEY AS C3, F0.C_PHONE AS C4, F0.C_ACCTBAL AS C5, F0.C_MKTSEGMENT AS C_0_0, F0.C_COMMENT AS C6
FROM CUSTOMER AS F0
WHERE (F0.C_MKTSEGMENT = 'BUILDING')) F0 JOIN (
SELECT F0.O_ORDERKEY AS L_ORDERKEY, F0.O_CUSTKEY AS C_CUSTKEY, F0.O_ORDERSTATUS AS O1, F0.O_TOTALPRICE AS O2, F0.O_ORDERDATE AS O_ORDERDATE, F0.O_ORDERPRIORITY AS O3, F0.O_CLERK AS O4, F0.O_SHIPPRIORITY AS O_SHIPPRIORITY, F0.O_COMMENT AS O5
FROM ORDERS AS F0) F1 ON ((F0.C_CUSTKEY = F1.C_CUSTKEY))) JOIN (
SELECT F0.L_ORDERKEY AS L_ORDERKEY, F0.L_PARTKEY AS X1, F0.L_SUPPKEY AS X2, F0.L_LINENUMBER AS X3, F0.L_QUANTITY AS X4, F0.L_EXTENDEDPRICE AS L_EXTENDEDPRICE, F0.L_DISCOUNT AS L_DISCOUNT, F0.L_TAX AS X5, F0.L_RETURNFLAG AS X6, F0.L_LINESTATUS AS X7, F0.L_SHIPDATE AS L_SHIPDATE, F0.L_COMMITDATE AS X8, F0.L_RECEIPTDATE AS X9, F0.L_SHIPINSTRUCT AS X10, F0.L_SHIPMODE AS X11, F0.L_COMMENT AS X12
FROM LINEITEM AS F0) F2 ON ((F1.L_ORDERKEY = F2.L_ORDERKEY)))
WHERE ((F1.O_ORDERDATE < '1995-03-15') AND (F2.L_SHIPDATE > '1995-03-15'))
GROUP BY F1.L_ORDERKEY, F1.O_ORDERDATE, F1.O_SHIPPRIORITY;
