CREATE TABLE rtpcq04 AS
SELECT F0.O_OPRIORITY AS A0, count(1) AS A1
FROM ((
SELECT F0.O_ORDERKEY AS L_OKEY, F0.O_CUSTKEY AS X1, F0.O_ORDERSTATUS AS X2, F0.O_TOTALPRICE AS X3, F0.O_ORDERDATE AS O_ODATE, F0.O_ORDERPRIORITY AS O_OPRIORITY, F0.O_CLERK AS X4, F0.O_SHIPPRIORITY AS X5, F0.O_COMMENT AS X6
FROM ORDERS AS F0) F0 JOIN (
SELECT F0.A0 AS L_OKEY
FROM (
SELECT  DISTINCT F0.L_OKEY AS A0
FROM (
SELECT F0.L_ORDERKEY AS L_OKEY, F0.L_PARTKEY AS X1, F0.L_SUPPKEY AS X2, F0.L_LINENUMBER AS X3, F0.L_QUANTITY AS X4, F0.L_EXTENDEDPRICE AS X5, F0.L_DISCOUNT AS X6, F0.L_TAX AS X7, F0.L_RETURNFLAG AS X8, F0.L_LINESTATUS AS X9, F0.L_SHIPDATE AS X10, F0.L_COMMITDATE AS L_COMM_DATE, F0.L_RECEIPTDATE AS L_RECEIPT_DATE, F0.L_SHIPINSTRUCT AS X11, F0.L_SHIPMODE AS X12, F0.L_COMMENT AS X13
FROM LINEITEM AS F0) F0
WHERE (F0.L_COMM_DATE < F0.L_RECEIPT_DATE)) F0) F1 ON ((F0.L_OKEY = F1.L_OKEY)))
WHERE ((F0.O_ODATE >= '1993-07-01') AND (F0.O_ODATE < '1993-10-01'))
GROUP BY F0.O_OPRIORITY;
