CREATE TABLE rtpcq07 AS
SELECT F0.A0 AS A0, F0.A1 AS A1, F0.A2 AS A2, sum(F0.A3) AS A3
FROM (
SELECT  DISTINCT F0.A0 AS A0, F0.A1 AS A1, F0.A2 AS A2, F0.A3 AS A3
FROM (SELECT * FROM (
SELECT  DISTINCT F4.SUPP_NATION AS A0, F5.CUST_NATION AS A1, F1.L_SD AS A2, (F1.L_EXTENDEDPRICE * (CAST (1 AS DOUBLE) - F1.L_DISCOUNT)) AS A3
FROM ((((((
SELECT F0.S_SUPPKEY AS L_SK, F0.S_NAME AS S2, F0.S_ADDRESS AS S3, F0.S_NATIONKEY AS S_NATIONKEY, F0.S_PHONE AS S4, F0.S_ACCTBAL AS S5, F0.S_COMMENT AS S6
FROM SUPPLIER AS F0) F0 JOIN (
SELECT F0.L_ORDERKEY AS L_OK, F0.L_PARTKEY AS L1, F0.L_SUPPKEY AS L_SK, F0.L_LINENUMBER AS L2, F0.L_QUANTITY AS L3, F0.L_EXTENDEDPRICE AS L_EXTENDEDPRICE, F0.L_DISCOUNT AS L_DISCOUNT, F0.L_TAX AS L6, F0.L_RETURNFLAG AS L7, F0.L_LINESTATUS AS L8, F0.L_SHIPDATE AS L_SD, F0.L_COMMITDATE AS L9, F0.L_RECEIPTDATE AS L10, F0.L_SHIPINSTRUCT AS L11, F0.L_SHIPMODE AS L12, F0.L_COMMENT AS L13
FROM LINEITEM AS F0) F1 ON ((F0.L_SK = F1.L_SK))) JOIN (
SELECT F0.O_ORDERKEY AS L_OK, F0.O_CUSTKEY AS L_CK, F0.O_ORDERSTATUS AS O1, F0.O_TOTALPRICE AS O2, F0.O_ORDERDATE AS O3, F0.O_ORDERPRIORITY AS O4, F0.O_CLERK AS O5, F0.O_SHIPPRIORITY AS O6, F0.O_COMMENT AS O7
FROM ORDERS AS F0) F2 ON ((F1.L_OK = F2.L_OK))) JOIN (
SELECT F0.C_CUSTKEY AS L_CK, F0.C_NAME AS C1, F0.C_ADDRESS AS C2, F0.C_NATIONKEY AS C_NATIONKEY, F0.C_PHONE AS C3, F0.C_ACCTBAL AS C4, F0.C_MKTSEGMENT AS C5, F0.C_COMMENT AS C6
FROM CUSTOMER AS F0) F3 ON ((F2.L_CK = F3.L_CK))) JOIN (
SELECT F0.N_NATIONKEY AS S_NATIONKEY, F0.N_NAME AS SUPP_NATION, F0.N_REGIONKEY AS N1, F0.N_COMMENT AS N2
FROM NATION AS F0) F4 ON ((F0.S_NATIONKEY = F4.S_NATIONKEY))) JOIN (
SELECT F0.N_NATIONKEY AS C_NATIONKEY, F0.N_NAME AS CUST_NATION, F0.N_REGIONKEY AS N3, F0.N_COMMENT AS N4
FROM NATION AS F0) F5 ON ((F3.C_NATIONKEY = F5.C_NATIONKEY)))
WHERE ((((F1.L_SD >= '1995-01-01') AND (F1.L_SD <= '1996-12-31')) AND (F4.SUPP_NATION = 'FRANCE')) AND (F5.CUST_NATION = 'GERMANY')) UNION ALL 
SELECT  DISTINCT F4.SUPP_NATION AS A0, F5.CUST_NATION AS A1, F1.L_SD AS A2, (F1.L_EXTENDEDPRICE * (CAST (1 AS DOUBLE) - F1.L_DISCOUNT)) AS A3
FROM ((((((
SELECT F0.S_SUPPKEY AS L_SK, F0.S_NAME AS S2, F0.S_ADDRESS AS S3, F0.S_NATIONKEY AS S_NATIONKEY, F0.S_PHONE AS S4, F0.S_ACCTBAL AS S5, F0.S_COMMENT AS S6
FROM SUPPLIER AS F0) F0 JOIN (
SELECT F0.L_ORDERKEY AS L_OK, F0.L_PARTKEY AS L1, F0.L_SUPPKEY AS L_SK, F0.L_LINENUMBER AS L2, F0.L_QUANTITY AS L3, F0.L_EXTENDEDPRICE AS L_EXTENDEDPRICE, F0.L_DISCOUNT AS L_DISCOUNT, F0.L_TAX AS L6, F0.L_RETURNFLAG AS L7, F0.L_LINESTATUS AS L8, F0.L_SHIPDATE AS L_SD, F0.L_COMMITDATE AS L9, F0.L_RECEIPTDATE AS L10, F0.L_SHIPINSTRUCT AS L11, F0.L_SHIPMODE AS L12, F0.L_COMMENT AS L13
FROM LINEITEM AS F0) F1 ON ((F0.L_SK = F1.L_SK))) JOIN (
SELECT F0.O_ORDERKEY AS L_OK, F0.O_CUSTKEY AS L_CK, F0.O_ORDERSTATUS AS O1, F0.O_TOTALPRICE AS O2, F0.O_ORDERDATE AS O3, F0.O_ORDERPRIORITY AS O4, F0.O_CLERK AS O5, F0.O_SHIPPRIORITY AS O6, F0.O_COMMENT AS O7
FROM ORDERS AS F0) F2 ON ((F1.L_OK = F2.L_OK))) JOIN (
SELECT F0.C_CUSTKEY AS L_CK, F0.C_NAME AS C1, F0.C_ADDRESS AS C2, F0.C_NATIONKEY AS C_NATIONKEY, F0.C_PHONE AS C3, F0.C_ACCTBAL AS C4, F0.C_MKTSEGMENT AS C5, F0.C_COMMENT AS C6
FROM CUSTOMER AS F0) F3 ON ((F2.L_CK = F3.L_CK))) JOIN (
SELECT F0.N_NATIONKEY AS S_NATIONKEY, F0.N_NAME AS SUPP_NATION, F0.N_REGIONKEY AS N1, F0.N_COMMENT AS N2
FROM NATION AS F0) F4 ON ((F0.S_NATIONKEY = F4.S_NATIONKEY))) JOIN (
SELECT F0.N_NATIONKEY AS C_NATIONKEY, F0.N_NAME AS CUST_NATION, F0.N_REGIONKEY AS N3, F0.N_COMMENT AS N4
FROM NATION AS F0) F5 ON ((F3.C_NATIONKEY = F5.C_NATIONKEY)))
WHERE ((((F1.L_SD >= '1995-01-01') AND (F1.L_SD <= '1996-12-31')) AND (F4.SUPP_NATION = 'GERMANY')) AND (F5.CUST_NATION = 'FRANCE')))) F0) F0
 GROUP BY F0.A0, F0.A1, F0.A2
 LIMIT 1;
