Qfilter('FRANCE', 'GERMANY').
Qfilter('GERMANY', 'FRANCE').

Qsub(supp_nation,cust_nation,strftime('%Y',l_sd), l_extendedprice * (1 - l_discount)) :-
    supplier(l_sk,s2,s3,s_nationkey,s4,s5,s6),
    lineitem(l_ok,l1,l_sk,l2,l3,l_extendedprice,l_discount,l6,l7,l8,l_sd,l9,l10,l11,l12,l13),
    orders(l_ok,l_ck,o1,o2,o3,o4,o5,o6,o7),
    customer(l_ck, c1,c2,c_nationkey,c3,c4,c5,c6),
    nation(s_nationkey,supp_nation,n1,n2),
    nation(c_nationkey,cust_nation,n3,n4),
    l_sd >= '1995-01-01',
    l_sd <= '1996-12-31',
    Qfilter(supp_nation, cust_nation).

Q(supp_nation,cust_nation,l_year,sum(volume)) :- Qsub(supp_nation,cust_nation,l_year,volume).

ANS : Q.

RP(x1, x2, x3, x4) :- rtpcq07(x1, x2, x3, x4).

LINEAGE FOR lineitem FOR RESULTS FROM RP.
