CREATE TABLE rtpcq08 AS SELECT  DISTINCT F0.YEAR AS A0, (F0.X / F0.Y) AS A1
FROM (
SELECT F0.A0 AS YEAR, F0.A1 AS X, F0.A2 AS Y
FROM (
SELECT F0.A0 AS A0, sum((CASE  WHEN (F0.A2 = 'BRAZIL') THEN F0.A1 ELSE 0 END)) AS A1, sum(F0.A1) AS A2
FROM (
SELECT  DISTINCT strftime('%Y', F5.O_ODATE) AS A0, (F6.L_EXTEND * (CAST (1 AS DOUBLE) - F6.L_DISCOUNT)) AS A1, F1.N_NAME AS A2
FROM ((((((((
SELECT F0.S_SUPPKEY AS S_KEY, F0.S_NAME AS X1, F0.S_ADDRESS AS X2, F0.S_NATIONKEY AS S_NKEY, F0.S_PHONE AS X3, F0.S_ACCTBAL AS X4, F0.S_COMMENT AS X5
FROM SUPPLIER AS F0) F0 JOIN (
SELECT F0.N_NATIONKEY AS S_NKEY, F0.N_NAME AS N_NAME, F0.N_REGIONKEY AS X6, F0.N_COMMENT AS X7
FROM NATION AS F0) F1 ON ((F0.S_NKEY = F1.S_NKEY))) CROSS JOIN (
SELECT F0.C_CUSTKEY AS C_CKEY, F0.C_NAME AS X8, F0.C_ADDRESS AS X9, F0.C_NATIONKEY AS C_NKEY, F0.C_PHONE AS X10, F0.C_ACCTBAL AS X11, F0.C_MKTSEGMENT AS X12, F0.C_COMMENT AS X13
FROM CUSTOMER AS F0) F2) JOIN (
SELECT F0.N_NATIONKEY AS C_NKEY, F0.N_NAME AS X14, F0.N_REGIONKEY AS N_RKEY, F0.N_COMMENT AS X15
FROM NATION AS F0) F3 ON ((F2.C_NKEY = F3.C_NKEY))) JOIN (
SELECT F0.R_REGIONKEY AS N_RKEY, F0.R_NAME AS C_4_0, F0.R_COMMENT AS X16
FROM REGION AS F0
WHERE (F0.R_NAME = 'AMERICA')) F4 ON ((F3.N_RKEY = F4.N_RKEY))) CROSS JOIN (
SELECT F0.O_ORDERKEY AS O_OKEY, F0.O_CUSTKEY AS X17, F0.O_ORDERSTATUS AS X18, F0.O_TOTALPRICE AS X19, F0.O_ORDERDATE AS O_ODATE, F0.O_ORDERPRIORITY AS X20, F0.O_CLERK AS X21, F0.O_SHIPPRIORITY AS X22, F0.O_COMMENT AS X23
FROM ORDERS AS F0) F5) JOIN (
SELECT F0.L_ORDERKEY AS O_OKEY, F0.L_PARTKEY AS L_PKEY, F0.L_SUPPKEY AS S_KEY, F0.L_LINENUMBER AS X24, F0.L_QUANTITY AS X25, F0.L_EXTENDEDPRICE AS L_EXTEND, F0.L_DISCOUNT AS L_DISCOUNT, F0.L_TAX AS X26, F0.L_RETURNFLAG AS X27, F0.L_LINESTATUS AS X28, F0.L_SHIPDATE AS X29, F0.L_COMMITDATE AS X30, F0.L_RECEIPTDATE AS X31, F0.L_SHIPINSTRUCT AS X32, F0.L_SHIPMODE AS X33, F0.L_COMMENT AS X34
FROM LINEITEM AS F0) F6 ON (((F5.O_OKEY = F6.O_OKEY) AND (F0.S_KEY = F6.S_KEY)))) JOIN (
SELECT F0.P_PARTKEY AS L_PKEY, F0.P_NAME AS X35, F0.P_MFGR AS X36, F0.P_BRAND AS X37, F0.P_TYPE AS C_7_0, F0.P_SIZE AS X38, F0.P_CONTAINER AS X39, F0.P_RETAILPRICE AS X40, F0.P_COMMENT AS X41
FROM PART AS F0
WHERE (F0.P_TYPE = 'ECONOMY ANODIZED STEEL')) F7 ON ((F6.L_PKEY = F7.L_PKEY)))
WHERE ((F5.O_ODATE >= '1995-01-01') AND (F5.O_ODATE < '1996-12-31'))) F0
GROUP BY F0.A0) F0) F0
