CREATE TABLE rtpcq09 AS
SELECT F0.A0 AS A0, F0.A1 AS A1, sum(F0.A2) AS A2
FROM (
SELECT  DISTINCT F5.N_NAME AS A0, strftime('%Y',F4.O_ORDERDATE) AS A1, ((F2.L_EXTENDEDPRICE * (CAST (1 AS DOUBLE) - F2.L_DISCOUNT)) - (F3.PS_SUPPLYCOST * F2.L_QUANTITY)) AS A2
FROM ((((((
SELECT F0.P_PARTKEY AS P_PARTKEY, F0.P_NAME AS P_NAME, F0.P_MFGR AS X1, F0.P_BRAND AS X2, F0.P_TYPE AS X3, F0.P_SIZE AS X4, F0.P_CONTAINER AS X5, F0.P_RETAILPRICE AS X6, F0.P_COMMENT AS X7
FROM PART AS F0) F0 CROSS JOIN (
SELECT F0.S_SUPPKEY AS S_SUPPKEY, F0.S_NAME AS X8, F0.S_ADDRESS AS X9, F0.S_NATIONKEY AS S_NATIONKEY, F0.S_PHONE AS X10, F0.S_ACCTBAL AS X11, F0.S_COMMENT AS X12
FROM SUPPLIER AS F0) F1) JOIN (
SELECT F0.L_ORDERKEY AS L_ORDERKEY, F0.L_PARTKEY AS P_PARTKEY, F0.L_SUPPKEY AS S_SUPPKEY, F0.L_LINENUMBER AS X13, F0.L_QUANTITY AS L_QUANTITY, F0.L_EXTENDEDPRICE AS L_EXTENDEDPRICE, F0.L_DISCOUNT AS L_DISCOUNT, F0.L_TAX AS X14, F0.L_RETURNFLAG AS X15, F0.L_LINESTATUS AS X16, F0.L_SHIPDATE AS X17, F0.L_COMMITDATE AS X18, F0.L_RECEIPTDATE AS X19, F0.L_SHIPINSTRUCT AS X20, F0.L_SHIPMODE AS X21, F0.L_COMMENT AS X22
FROM LINEITEM AS F0) F2 ON (((F0.P_PARTKEY = F2.P_PARTKEY) AND (F1.S_SUPPKEY = F2.S_SUPPKEY)))) JOIN (
SELECT F0.PS_PARTKEY AS P_PARTKEY, F0.PS_SUPPKEY AS S_SUPPKEY, F0.PS_AVAILQTY AS X24, F0.PS_SUPPLYCOST AS PS_SUPPLYCOST, F0.PS_COMMENT AS X25
FROM PARTSUPP AS F0) F3 ON (((((F0.P_PARTKEY = F3.P_PARTKEY) AND (F2.P_PARTKEY = F3.P_PARTKEY)) AND (F1.S_SUPPKEY = F3.S_SUPPKEY)) AND (F2.S_SUPPKEY = F3.S_SUPPKEY)))) JOIN (
SELECT F0.O_ORDERKEY AS L_ORDERKEY, F0.O_CUSTKEY AS X26, F0.O_ORDERSTATUS AS X27, F0.O_TOTALPRICE AS X28, F0.O_ORDERDATE AS O_ORDERDATE, F0.O_ORDERPRIORITY AS X30, F0.O_CLERK AS X31, F0.O_SHIPPRIORITY AS X32, F0.O_COMMENT AS X33
FROM ORDERS AS F0) F4 ON ((F2.L_ORDERKEY = F4.L_ORDERKEY))) JOIN (
SELECT F0.N_NATIONKEY AS S_NATIONKEY, F0.N_NAME AS N_NAME, F0.N_REGIONKEY AS X34, F0.N_COMMENT AS X35
FROM NATION AS F0) F5 ON ((F1.S_NATIONKEY = F5.S_NATIONKEY)))
WHERE (F0.P_NAME LIKE '%green%')) F0
GROUP BY F0.A0, F0.A1;
