CREATE TABLE rtpcq10 AS
SELECT F0.C_CK AS A0, F0.C_N AS A1, sum((F2.L_EP * (CAST (1 AS DOUBLE) - F2.L_D))) AS A2, F0.C_AB AS A3, F3.N_N AS A4, F0.C_A AS A5, F0.C_P AS A6, F0.C_C AS A7
FROM ((((
SELECT F0.C_CUSTKEY AS C_CK, F0.C_NAME AS C_N, F0.C_ADDRESS AS C_A, F0.C_NATIONKEY AS C_NK, F0.C_PHONE AS C_P, F0.C_ACCTBAL AS C_AB, F0.C_MKTSEGMENT AS C1, F0.C_COMMENT AS C_C
FROM CUSTOMER AS F0) F0 JOIN (
SELECT F0.O_ORDERKEY AS O_OK, F0.O_CUSTKEY AS C_CK, F0.O_ORDERSTATUS AS O1, F0.O_TOTALPRICE AS O2, F0.O_ORDERDATE AS O_OD, F0.O_ORDERPRIORITY AS O3, F0.O_CLERK AS O4, F0.O_SHIPPRIORITY AS O5, F0.O_COMMENT AS O6
FROM ORDERS AS F0) F1 ON ((F0.C_CK = F1.C_CK))) JOIN (
SELECT F0.L_ORDERKEY AS O_OK, F0.L_PARTKEY AS L1, F0.L_SUPPKEY AS L2, F0.L_LINENUMBER AS L3, F0.L_QUANTITY AS L4, F0.L_EXTENDEDPRICE AS L_EP, F0.L_DISCOUNT AS L_D, F0.L_TAX AS L5, F0.L_RETURNFLAG AS C_2_0, F0.L_LINESTATUS AS L6, F0.L_SHIPDATE AS L7, F0.L_COMMITDATE AS L8, F0.L_RECEIPTDATE AS L9, F0.L_SHIPINSTRUCT AS L10, F0.L_SHIPMODE AS L11, F0.L_COMMENT AS L12
FROM LINEITEM AS F0
WHERE (F0.L_RETURNFLAG = 'R')) F2 ON ((F1.O_OK = F2.O_OK))) JOIN (
SELECT F0.N_NATIONKEY AS C_NK, F0.N_NAME AS N_N, F0.N_REGIONKEY AS N2, F0.N_COMMENT AS N3
FROM NATION AS F0) F3 ON ((F0.C_NK = F3.C_NK)))
WHERE ((F1.O_OD >= '1993-10-01') AND (F1.O_OD < '1994-01-01'))
GROUP BY F0.C_CK, F0.C_N, F0.C_AB, F3.N_N, F0.C_A, F0.C_P, F0.C_C;
