Q1(l_okey,l_linenumber,l_shipmode) :-
    lineitem(l_okey,x8,x9,l_linenumber,x11,x12,x13,x14,x15,x16,l_shipdate,l_commitdate,l_receiptdate,x17,l_shipmode,x18),
    l_commitdate < l_receiptdate,
    l_shipdate < l_commitdate,
    l_receiptdate >= '1994-01-01',
    l_receiptdate < '1995-01-01'.

Q2(l_okey,l_linenumber,l_shipmode) :- Q1(l_okey,l_linenumber,l_shipmode),l_shipmode = 'SHIP'.
Q2(l_okey,l_linenumber,l_shipmode) :- Q1(l_okey,l_linenumber,l_shipmode),l_shipmode = 'MAIL'.

Q(l_shipmode,
  sum(CASE WHEN o_orderpriority = '1-URGENT' THEN 1
           WHEN o_orderpriority = '2-HIGH' THEN 1
           ELSE 0
           END),
  sum(CASE WHEN o_orderpriority <> '1-URGENT'
           THEN (CASE WHEN o_orderpriority <> '2-HIGH' THEN 1 ELSE 0 END)
           ELSE 0
           END))
:-
orders(o_okey,x1,x2,x3,x4,o_orderpriority,x5,x6,x7),
Q2(o_okey,l_linenumber,l_shipmode).

ANS:Q.
