CREATE TABLE rtpcq12 AS
  SELECT F1.L_SHIPMODE AS A0, sum((CASE  WHEN (F0.O_ORDERPRIORITY = '1-URGENT') THEN 1 WHEN (F0.O_ORDERPRIORITY = '2-HIGH') THEN 1 ELSE 0 END)) AS A1, sum((CASE  WHEN (F0.O_ORDERPRIORITY <> '1-URGENT') THEN (CASE  WHEN (F0.O_ORDERPRIORITY <> '2-HIGH') THEN 1 ELSE 0 END) ELSE 0 END)) AS A2
    FROM ((
      SELECT F0.O_ORDERKEY AS O_OKEY, F0.O_CUSTKEY AS X1, F0.O_ORDERSTATUS AS X2, F0.O_TOTALPRICE AS X3, F0.O_ORDERDATE AS X4, F0.O_ORDERPRIORITY AS O_ORDERPRIORITY, F0.O_CLERK AS X5, F0.O_SHIPPRIORITY AS X6, F0.O_COMMENT AS X7
        FROM ORDERS AS F0) F0 JOIN (
          SELECT F0.A0 AS O_OKEY, F0.A1 AS L_LINENUMBER, F0.A2 AS L_SHIPMODE
            FROM (
              SELECT  DISTINCT F0.A0 AS A0, F0.A1 AS A1, F0.A2 AS A2
                FROM (SELECT * FROM (
                  SELECT  DISTINCT F0.L_OKEY AS A0, F0.L_LINENUMBER AS A1, F0.L_SHIPMODE AS A2
                    FROM (
                      SELECT F0.A0 AS L_OKEY, F0.A1 AS L_LINENUMBER, F0.A2 AS L_SHIPMODE
                        FROM (
                          SELECT  DISTINCT F0.L_OKEY AS A0, F0.L_LINENUMBER AS A1, F0.L_SHIPMODE AS A2
                            FROM (
                              SELECT F0.L_ORDERKEY AS L_OKEY, F0.L_PARTKEY AS X8, F0.L_SUPPKEY AS X9, F0.L_LINENUMBER AS L_LINENUMBER, F0.L_QUANTITY AS X11, F0.L_EXTENDEDPRICE AS X12, F0.L_DISCOUNT AS X13, F0.L_TAX AS X14, F0.L_RETURNFLAG AS X15, F0.L_LINESTATUS AS X16, F0.L_SHIPDATE AS L_SHIPDATE, F0.L_COMMITDATE AS L_COMMITDATE, F0.L_RECEIPTDATE AS L_RECEIPTDATE, F0.L_SHIPINSTRUCT AS X17, F0.L_SHIPMODE AS L_SHIPMODE, F0.L_COMMENT AS X18
                                FROM LINEITEM AS F0) F0
                           WHERE ((((F0.L_COMMITDATE < F0.L_RECEIPTDATE) AND (F0.L_SHIPDATE < F0.L_COMMITDATE)) AND (F0.L_RECEIPTDATE >= '1994-01-01')) AND (F0.L_RECEIPTDATE < '1995-01-01'))) F0) F0
                   WHERE (F0.L_SHIPMODE = 'SHIP') UNION ALL 
                  SELECT  DISTINCT F0.L_OKEY AS A0, F0.L_LINENUMBER AS A1, F0.L_SHIPMODE AS A2
                    FROM (
                      SELECT F0.A0 AS L_OKEY, F0.A1 AS L_LINENUMBER, F0.A2 AS L_SHIPMODE
                        FROM (
                          SELECT  DISTINCT F0.L_OKEY AS A0, F0.L_LINENUMBER AS A1, F0.L_SHIPMODE AS A2
                            FROM (
                              SELECT F0.L_ORDERKEY AS L_OKEY, F0.L_PARTKEY AS X8, F0.L_SUPPKEY AS X9, F0.L_LINENUMBER AS L_LINENUMBER, F0.L_QUANTITY AS X11, F0.L_EXTENDEDPRICE AS X12, F0.L_DISCOUNT AS X13, F0.L_TAX AS X14, F0.L_RETURNFLAG AS X15, F0.L_LINESTATUS AS X16, F0.L_SHIPDATE AS L_SHIPDATE, F0.L_COMMITDATE AS L_COMMITDATE, F0.L_RECEIPTDATE AS L_RECEIPTDATE, F0.L_SHIPINSTRUCT AS X17, F0.L_SHIPMODE AS L_SHIPMODE, F0.L_COMMENT AS X18
                                FROM LINEITEM AS F0) F0
                           WHERE ((((F0.L_COMMITDATE < F0.L_RECEIPTDATE) AND (F0.L_SHIPDATE < F0.L_COMMITDATE)) AND (F0.L_RECEIPTDATE >= '1994-01-01')) AND (F0.L_RECEIPTDATE < '1995-01-01'))) F0) F0
                   WHERE (F0.L_SHIPMODE = 'MAIL'))) F0) F0) F1 ON ((F0.O_OKEY = F1.O_OKEY)))
   GROUP BY F1.L_SHIPMODE
   LIMIT 1;
