CREATE TABLE rtpcq13 AS
  SELECT F0.A1 AS A0, count(1) AS A1
    FROM (
      SELECT /*+ materialize */ F0.C_CUSTKEY AS A0, count(F1.O_ORDERKEY) AS A1
        FROM ((
          SELECT F0.C_CUSTKEY AS C_CUSTKEY, F0.C_NAME AS C1, F0.C_ADDRESS AS C2, F0.C_NATIONKEY AS C3, F0.C_PHONE AS C4, F0.C_ACCTBAL AS C5, F0.C_MKTSEGMENT AS C6, F0.C_COMMENT AS C7
            FROM CUSTOMER AS F0) F0 JOIN (
              SELECT F0.O_ORDERKEY AS O_ORDERKEY, F0.O_CUSTKEY AS C_CUSTKEY, F0.O_ORDERSTATUS AS O1, F0.O_TOTALPRICE AS O2, F0.O_ORDERDATE AS O3, F0.O_ORDERPRIORITY AS O4, F0.O_CLERK AS O5, F0.O_SHIPPRIORITY AS O6, F0.O_COMMENT AS O7
                FROM ORDERS AS F0) F1 ON ((F0.C_CUSTKEY = F1.C_CUSTKEY)))
       GROUP BY F0.C_CUSTKEY) F0
   GROUP BY F0.A1
   LIMIT 1;
