CREATE TABLE rtpcq14 AS
SELECT  DISTINCT (100 * (F0.X / F0.Y)) AS A0
FROM (
SELECT /*+ materialize */ F0.A0 AS X, F0.A1 AS Y
FROM (
SELECT /*+ materialize */ sum((CASE  WHEN (F0.P_TYPE LIKE 'PROMO%') THEN (F1.L_EXTP * (1 - F1.L_DISCOUNT)) ELSE 0 END)) AS A0, sum((F1.L_EXTP * (CAST (1 AS DOUBLE) - F1.L_DISCOUNT))) AS A1
FROM ((
SELECT F0.P_PARTKEY AS P_PARTKEY, F0.P_NAME AS P1, F0.P_MFGR AS P2, F0.P_BRAND AS P3, F0.P_TYPE AS P_TYPE, F0.P_SIZE AS P4, F0.P_CONTAINER AS P5, F0.P_RETAILPRICE AS P6, F0.P_COMMENT AS P7
FROM PART AS F0) F0 JOIN (
SELECT F0.L_ORDERKEY AS L1, F0.L_PARTKEY AS P_PARTKEY, F0.L_SUPPKEY AS L2, F0.L_LINENUMBER AS L3, F0.L_QUANTITY AS L4, F0.L_EXTENDEDPRICE AS L_EXTP, F0.L_DISCOUNT AS L_DISCOUNT, F0.L_TAX AS L5, F0.L_RETURNFLAG AS L6, F0.L_LINESTATUS AS L7, F0.L_SHIPDATE AS L_SHIPDATE, F0.L_COMMITDATE AS L8, F0.L_RECEIPTDATE AS L9, F0.L_SHIPINSTRUCT AS L10, F0.L_SHIPMODE AS L11, F0.L_COMMENT AS L12
FROM LINEITEM AS F0) F1 ON ((F0.P_PARTKEY = F1.P_PARTKEY)))
 WHERE ((F1.L_SHIPDATE >= '1995-09-01') AND (F1.L_SHIPDATE < '1995-10-01'))) F0) F0
 LIMIT 1;
