CREATE TABLE rtpcq15 AS
  SELECT  DISTINCT F0.S_SUPPKEY AS A0, F0.S_NAME AS A1, F0.S_ADDRESS AS A2, F0.S_PHONE AS A3, F1.REV AS A4
    FROM (((
      SELECT F0.S_SUPPKEY AS S_SUPPKEY, F0.S_NAME AS S_NAME, F0.S_ADDRESS AS S_ADDRESS, F0.S_NATIONKEY AS S1, F0.S_PHONE AS S_PHONE, F0.S_ACCTBAL AS S2, F0.S_COMMENT AS S3
        FROM SUPPLIER AS F0) F0 JOIN (
          SELECT F0.A0 AS S_SUPPKEY, F0.A1 AS REV
            FROM (
              SELECT /*+ materialize */ F0.L_SUPPKEY AS A0, sum((F0.L_EXTP * (CAST (1 AS DOUBLE) - F0.L_DISCOUNT))) AS A1
                FROM (
                  SELECT F0.L_ORDERKEY AS L1, F0.L_PARTKEY AS L2, F0.L_SUPPKEY AS L_SUPPKEY, F0.L_LINENUMBER AS L3, F0.L_QUANTITY AS L4, F0.L_EXTENDEDPRICE AS L_EXTP, F0.L_DISCOUNT AS L_DISCOUNT, F0.L_TAX AS L5, F0.L_RETURNFLAG AS L6, F0.L_LINESTATUS AS L7, F0.L_SHIPDATE AS L_SHIPDATE, F0.L_COMMITDATE AS L8, F0.L_RECEIPTDATE AS L9, F0.L_SHIPINSTRUCT AS L10, F0.L_SHIPMODE AS L11, F0.L_COMMENT AS L12
                    FROM LINEITEM AS F0) F0
               WHERE ((F0.L_SHIPDATE >= '1996-01-01') AND (F0.L_SHIPDATE < '1996-04-01'))
               GROUP BY F0.L_SUPPKEY) F0) F1 ON ((F0.S_SUPPKEY = F1.S_SUPPKEY))) JOIN (
                 SELECT F0.A0 AS REV
                   FROM (
                     SELECT /*+ materialize */ max(F0.A1) AS A0
                       FROM (
                         SELECT /*+ materialize */ F0.L_SUPPKEY AS A0, sum((F0.L_EXTP * (CAST (1 AS DOUBLE) - F0.L_DISCOUNT))) AS A1
                           FROM (
                             SELECT F0.L_ORDERKEY AS L1, F0.L_PARTKEY AS L2, F0.L_SUPPKEY AS L_SUPPKEY, F0.L_LINENUMBER AS L3, F0.L_QUANTITY AS L4, F0.L_EXTENDEDPRICE AS L_EXTP, F0.L_DISCOUNT AS L_DISCOUNT, F0.L_TAX AS L5, F0.L_RETURNFLAG AS L6, F0.L_LINESTATUS AS L7, F0.L_SHIPDATE AS L_SHIPDATE, F0.L_COMMITDATE AS L8, F0.L_RECEIPTDATE AS L9, F0.L_SHIPINSTRUCT AS L10, F0.L_SHIPMODE AS L11, F0.L_COMMENT AS L12
                               FROM LINEITEM AS F0) F0
                          WHERE ((F0.L_SHIPDATE >= '1996-01-01') AND (F0.L_SHIPDATE < '1996-04-01'))
                          GROUP BY F0.L_SUPPKEY) F0) F0) F2 ON ((F1.REV = F2.REV)))
   LIMIT 1;
