Q(p_brand,p_type,p_size,count(s_suppkey)):-
partsupp(p_partkey,s_suppkey,ps1,ps2,ps3),
part(p_partkey,p1,p2,p_brand,p_type,p_size,p3,p4,p5),
supplier(s_suppkey,s1,s2,s3,s4,s5,s_comment),
p_brand != 'Brand#45',
p_size = 49.

Q(p_brand,p_type,p_size,count(s_suppkey)):-
partsupp(p_partkey,s_suppkey,ps1,ps2,ps3),
part(p_partkey,p1,p2,p_brand,p_type,p_size,p3,p4,p5),
supplier(s_suppkey,s1,s2,s3,s4,s5,s_comment),
p_brand != 'Brand#45',
p_size = 14.

Q(p_brand,p_type,p_size,count(s_suppkey)):-
partsupp(p_partkey,s_suppkey,ps1,ps2,ps3),
part(p_partkey,p1,p2,p_brand,p_type,p_size,p3,p4,p5),
supplier(s_suppkey,s1,s2,s3,s4,s5,s_comment),
p_brand != 'Brand#45',
p_size = 23.

Q(p_brand,p_type,p_size,count(s_suppkey)):-
partsupp(p_partkey,s_suppkey,ps1,ps2,ps3),
part(p_partkey,p1,p2,p_brand,p_type,p_size,p3,p4,p5),
supplier(s_suppkey,s1,s2,s3,s4,s5,s_comment),
p_brand != 'Brand#45',
p_size = 45.

Q(p_brand,p_type,p_size,count(s_suppkey)):-
partsupp(p_partkey,s_suppkey,ps1,ps2,ps3),
part(p_partkey,p1,p2,p_brand,p_type,p_size,p3,p4,p5),
supplier(s_suppkey,s1,s2,s3,s4,s5,s_comment),
p_brand != 'Brand#45',
p_size = 19.

Q(p_brand,p_type,p_size,count(s_suppkey)):-
partsupp(p_partkey,s_suppkey,ps1,ps2,ps3),
part(p_partkey,p1,p2,p_brand,p_type,p_size,p3,p4,p5),
supplier(s_suppkey,s1,s2,s3,s4,s5,s_comment),
p_brand != 'Brand#45',
p_size = 3.


Q(p_brand,p_type,p_size,count(s_suppkey)):-
partsupp(p_partkey,s_suppkey,ps1,ps2,ps3),
part(p_partkey,p1,p2,p_brand,p_type,p_size,p3,p4,p5),
supplier(s_suppkey,s1,s2,s3,s4,s5,s_comment),
p_brand != 'Brand#45',
p_size = 36.

Q(p_brand,p_type,p_size,count(s_suppkey)):-
partsupp(p_partkey,s_suppkey,ps1,ps2,ps3),
part(p_partkey,p1,p2,p_brand,p_type,p_size,p3,p4,p5),
supplier(s_suppkey,s1,s2,s3,s4,s5,s_comment),
p_brand != 'Brand#45',
p_size = 9.

ANS: Q.

RP(x1, x2, x3, x4) :- rtpcq16(x1, x2, x3, x4).

LINEAGE FOR partsupp FOR RESULTS FROM RP.
