CREATE TABLE rtpcq17 AS
  SELECT sum((F2.L_EP / 7.000000)) AS A0
  FROM (((
    SELECT F0.A0 AS L_PK, F0.A1 AS Q2
      FROM (
        SELECT /*+ materialize */ F0.L_PARTKEY AS A0, avg((0.200000 * F0.L_QUANTITY)) AS A1
          FROM LINEITEM AS F0
         GROUP BY F0.L_PARTKEY) F0) F0 JOIN (
           SELECT F0.P_PARTKEY AS L_PK, F0.P_NAME AS P1, F0.P_MFGR AS P2, F0.P_BRAND AS C_1_0, F0.P_TYPE AS P3, F0.P_SIZE AS P4, F0.P_CONTAINER AS C_1_1, F0.P_RETAILPRICE AS P5, F0.P_COMMENT AS P6
             FROM PART AS F0
            WHERE ((F0.P_BRAND = 'Brand#23') AND (F0.P_CONTAINER = 'MED BOX'))) F1 ON ((F0.L_PK = F1.L_PK))) JOIN (
              SELECT F0.L_ORDERKEY AS L1, F0.L_PARTKEY AS L_PK, F0.L_SUPPKEY AS L2, F0.L_LINENUMBER AS L3, F0.L_QUANTITY AS L_Q, F0.L_EXTENDEDPRICE AS L_EP, F0.L_DISCOUNT AS L4, F0.L_TAX AS L5, F0.L_RETURNFLAG AS L6, F0.L_LINESTATUS AS L7, F0.L_SHIPDATE AS L8, F0.L_COMMITDATE AS L9, F0.L_RECEIPTDATE AS L10, F0.L_SHIPINSTRUCT AS L11, F0.L_SHIPMODE AS L12, F0.L_COMMENT AS L13
                FROM LINEITEM AS F0) F2 ON (((F0.L_PK = F2.L_PK) AND (F1.L_PK = F2.L_PK))))
  WHERE (CAST (F2.L_Q AS TEXT) < F0.Q2)
  LIMIT 1;
