CREATE TABLE rtpcq18 AS
  SELECT F0.C_NAME AS A0, F0.C_CUSTKEY AS A1, F1.O_ORDERKEY AS A2, F1.O_ORDERDATE AS A3, F1.O_TOTALPRICE AS A4, sum(F2.L_QUANTITY) AS A5
    FROM ((((
      SELECT F0.C_CUSTKEY AS C_CUSTKEY, F0.C_NAME AS C_NAME, F0.C_ADDRESS AS C1, F0.C_NATIONKEY AS C2, F0.C_PHONE AS C3, F0.C_ACCTBAL AS C4, F0.C_MKTSEGMENT AS C5, F0.C_COMMENT AS C6
        FROM CUSTOMER AS F0) F0 JOIN (
          SELECT F0.O_ORDERKEY AS O_ORDERKEY, F0.O_CUSTKEY AS C_CUSTKEY, F0.O_ORDERSTATUS AS O1, F0.O_TOTALPRICE AS O_TOTALPRICE, F0.O_ORDERDATE AS O_ORDERDATE, F0.O_ORDERPRIORITY AS O2, F0.O_CLERK AS O3, F0.O_SHIPPRIORITY AS O4, F0.O_COMMENT AS O5
            FROM ORDERS AS F0) F1 ON ((F0.C_CUSTKEY = F1.C_CUSTKEY))) JOIN (
              SELECT F0.L_ORDERKEY AS O_ORDERKEY, F0.L_PARTKEY AS X1, F0.L_SUPPKEY AS X2, F0.L_LINENUMBER AS X3, F0.L_QUANTITY AS L_QUANTITY, F0.L_EXTENDEDPRICE AS X4, F0.L_DISCOUNT AS X5, F0.L_TAX AS X6, F0.L_RETURNFLAG AS X7, F0.L_LINESTATUS AS X8, F0.L_SHIPDATE AS X9, F0.L_COMMITDATE AS X10, F0.L_RECEIPTDATE AS X11, F0.L_SHIPINSTRUCT AS X12, F0.L_SHIPMODE AS X13, F0.L_COMMENT AS X14
                FROM LINEITEM AS F0) F2 ON ((F1.O_ORDERKEY = F2.O_ORDERKEY))) JOIN (
                  SELECT F0.A0 AS O_ORDERKEY, F0.A1 AS T1
                    FROM (
                      SELECT /*+ materialize */ F0.L_ORDERKEY AS A0, sum(F0.L_QUANTITY) AS A1
                        FROM LINEITEM AS F0
                       GROUP BY F0.L_ORDERKEY) F0) F3 ON (((F1.O_ORDERKEY = F3.O_ORDERKEY) AND (F2.O_ORDERKEY = F3.O_ORDERKEY))))
   WHERE (F3.T1 > CAST (300 AS TEXT))
   GROUP BY F0.C_NAME, F0.C_CUSTKEY, F1.O_ORDERKEY, F1.O_ORDERDATE, F1.O_TOTALPRICE
   LIMIT 1;  
