Q1(l_partkey,l_suppkey,sum(0.5*l_quantity)) :-
    lineitem(l1,l_partkey,l_suppkey,l2,l_quantity,l3,l4,l5,l6,l7,l_shipdate,l8,l9,l10,l11,l12),
    l_shipdate >= '1994-01-01',
    l_shipdate < '1995-01-01'.

Q2(s_suppkey) :-
    part(p_partkey, p_name,p1,p2,p3,p4,p5,p6,p7),
    partsupp(p_partkey,s_suppkey,s_available,s1,s2),
    Q1(p_partkey,s_suppkey,quantity),
    s_available > quantity,
    p_name LIKE 'forest%'.

Q(s_name,s_address) :-
    supplier(s_suppkey,s_name,s_address,n_nationkey,s1,s2,s3),
    nation(n_nationkey,'CANADA',n1,n2),
    Q2(s_suppkey).

ANS: Q.
