CREATE TABLE rtpcq20 AS
SELECT  DISTINCT F0.S_NAME AS A0, F0.S_ADDRESS AS A1
FROM (((
SELECT F0.S_SUPPKEY AS S_SUPPKEY, F0.S_NAME AS S_NAME, F0.S_ADDRESS AS S_ADDRESS, F0.S_NATIONKEY AS N_NATIONKEY, F0.S_PHONE AS S1, F0.S_ACCTBAL AS S2, F0.S_COMMENT AS S3
FROM SUPPLIER AS F0) F0 JOIN (
SELECT F0.N_NATIONKEY AS N_NATIONKEY, F0.N_NAME AS C_1_0, F0.N_REGIONKEY AS N1, F0.N_COMMENT AS N2
FROM NATION AS F0
WHERE (F0.N_NAME = 'CANADA')) F1 ON ((F0.N_NATIONKEY = F1.N_NATIONKEY))) JOIN (
SELECT F0.A0 AS S_SUPPKEY
FROM (
SELECT  DISTINCT F1.S_SUPPKEY AS A0
FROM (((
SELECT F0.P_PARTKEY AS P_PARTKEY, F0.P_NAME AS P_NAME, F0.P_MFGR AS P1, F0.P_BRAND AS P2, F0.P_TYPE AS P3, F0.P_SIZE AS P4, F0.P_CONTAINER AS P5, F0.P_RETAILPRICE AS P6, F0.P_COMMENT AS P7
FROM PART AS F0) F0 JOIN (
SELECT F0.PS_PARTKEY AS P_PARTKEY, F0.PS_SUPPKEY AS S_SUPPKEY, F0.PS_AVAILQTY AS S_AVAILABLE, F0.PS_SUPPLYCOST AS S1, F0.PS_COMMENT AS S2
FROM PARTSUPP AS F0) F1 ON ((F0.P_PARTKEY = F1.P_PARTKEY))) JOIN (
SELECT F0.A0 AS P_PARTKEY, F0.A1 AS S_SUPPKEY, F0.A2 AS QUANTITY
FROM (
SELECT /*+ materialize */ F0.L_PARTKEY AS A0, F0.L_SUPPKEY AS A1, sum((0.500000 * F0.L_QUANTITY)) AS A2
FROM (
SELECT F0.L_ORDERKEY AS L1, F0.L_PARTKEY AS L_PARTKEY, F0.L_SUPPKEY AS L_SUPPKEY, F0.L_LINENUMBER AS L2, F0.L_QUANTITY AS L_QUANTITY, F0.L_EXTENDEDPRICE AS L3, F0.L_DISCOUNT AS L4, F0.L_TAX AS L5, F0.L_RETURNFLAG AS L6, F0.L_LINESTATUS AS L7, F0.L_SHIPDATE AS L_SHIPDATE, F0.L_COMMITDATE AS L8, F0.L_RECEIPTDATE AS L9, F0.L_SHIPINSTRUCT AS L10, F0.L_SHIPMODE AS L11, F0.L_COMMENT AS L12
FROM LINEITEM AS F0) F0
WHERE ((F0.L_SHIPDATE >= '1994-01-01') AND (F0.L_SHIPDATE < '1995-01-01'))
GROUP BY F0.L_PARTKEY, F0.L_SUPPKEY) F0) F2 ON ((((F0.P_PARTKEY = F2.P_PARTKEY) AND (F1.P_PARTKEY = F2.P_PARTKEY)) AND (F1.S_SUPPKEY = F2.S_SUPPKEY))))
WHERE ((CAST (F1.S_AVAILABLE AS TEXT) > F2.QUANTITY) AND (F0.P_NAME LIKE 'forest%'))) F0) F2 ON ((F0.S_SUPPKEY = F2.S_SUPPKEY)))
  LIMIT 1;
