#line 2 "postgres_parser.lex.c"

#line 4 "postgres_parser.lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer postgres_create_buffer
#define yy_delete_buffer postgres_delete_buffer
#define yy_flex_debug postgres_flex_debug
#define yy_init_buffer postgres_init_buffer
#define yy_flush_buffer postgres_flush_buffer
#define yy_load_buffer_state postgres_load_buffer_state
#define yy_switch_to_buffer postgres_switch_to_buffer
#define yyin postgresin
#define yyleng postgresleng
#define yylex postgreslex
#define yylineno postgreslineno
#define yyout postgresout
#define yyrestart postgresrestart
#define yytext postgrestext
#define yywrap postgreswrap
#define yyalloc postgresalloc
#define yyrealloc postgresrealloc
#define yyfree postgresfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE postgresrestart(postgresin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t postgresleng;

extern FILE *postgresin, *postgresout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE postgreslex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-postgreslineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < postgresleng; ++yyl )\
                    if ( postgrestext[yyl] == '\n' )\
                        --postgreslineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up postgrestext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up postgrestext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via postgresrestart()), so that the user can continue scanning by
	 * just pointing postgresin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when postgrestext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t postgresleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow postgreswrap()'s to do buffer switches
 * instead of setting up a fresh postgresin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void postgresrestart (FILE *input_file  );
void postgres_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE postgres_create_buffer (FILE *file,int size  );
void postgres_delete_buffer (YY_BUFFER_STATE b  );
void postgres_flush_buffer (YY_BUFFER_STATE b  );
void postgrespush_buffer_state (YY_BUFFER_STATE new_buffer  );
void postgrespop_buffer_state (void );

static void postgresensure_buffer_stack (void );
static void postgres_load_buffer_state (void );
static void postgres_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER postgres_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE postgres_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE postgres_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE postgres_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *postgresalloc (yy_size_t  );
void *postgresrealloc (void *,yy_size_t  );
void postgresfree (void *  );

#define yy_new_buffer postgres_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        postgresensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            postgres_create_buffer(postgresin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        postgresensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            postgres_create_buffer(postgresin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define postgreswrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *postgresin = (FILE *) 0, *postgresout = (FILE *) 0;

typedef int yy_state_type;

extern int postgreslineno;

int postgreslineno = 1;

extern char *postgrestext;
#define yytext_ptr postgrestext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up postgrestext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	postgresleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 101
#define YY_END_OF_BUFFER 102
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[378] =
    {   0,
        0,    0,    0,    0,  102,  100,    1,    1,   95,  100,
       95,  100,   93,   95,   93,   96,  100,   94,   94,   94,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,    1,   94,    0,    0,   99,   98,    1,
       97,   97,   96,    0,   92,   90,    0,   90,   90,   90,
       10,   90,   90,   90,   26,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   44,
       29,   90,   90,   90,   90,   90,   90,   90,   90,   90,
        8,   13,   17,   90,   90,   90,   90,   90,   90,   90,

       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   91,
        1,   97,    0,   97,   92,    0,   90,   15,   16,   23,
       83,   18,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   66,   90,   90,   90,   90,   90,
       62,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       20,   19,   90,   48,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   75,   57,   90,    6,   90,
       90,   90,   21,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   82,   90,   90,   90,   90,   90,   90,   90,

       90,   90,   63,   90,   90,   90,   90,   90,   84,   90,
       67,   90,   90,   90,    9,   90,   90,   90,   90,   90,
       42,   34,   87,   35,   46,   90,   90,   90,   30,   78,
       90,   90,   68,   90,   90,   90,   90,   90,   90,   70,
       90,   80,   24,   90,   90,   65,   90,   90,   90,   59,
       90,   90,   90,   90,   90,   90,   64,   90,   61,   55,
       90,   52,   90,   90,   22,   41,   90,   90,   90,   90,
       86,   90,   47,   90,   38,   90,   90,   50,   33,   90,
       85,   51,   37,   90,   90,   90,   71,   36,   90,   90,
       90,   77,   90,   90,   88,   90,   31,   90,   40,   90,

       90,   11,   90,   90,   53,   90,    5,   90,   45,   90,
       49,    3,   90,   90,   90,   90,   90,   90,   90,    2,
       14,   90,   90,   90,    4,   43,   90,   90,   25,   74,
       90,   90,   90,   90,   39,   90,   90,   90,   90,   90,
       90,   90,   79,   90,   90,   12,   90,   90,   90,   90,
       90,   90,   54,   90,   90,   90,   89,   90,   76,   90,
       32,   69,   73,   90,   58,   90,   72,   90,   90,    7,
       90,   90,   90,   60,   56,   81,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       10,    8,   11,   10,   12,   13,    8,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,   10,   16,
       17,   18,   19,    1,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   36,
        1,    1,    1,    8,   19,    1,   45,   46,   47,   48,

       49,   50,   51,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   36,   61,   62,   63,   64,   65,   66,   67,
       68,   36,    1,    8,    1,    8,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[69] =
    {   0,
        1,    1,    2,    2,    1,    3,    4,    1,    1,    1,
        1,    1,    4,    4,    1,    1,    1,    1,    4,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5
    } ;

static yyconst flex_int16_t yy_base[384] =
    {   0,
        0,    0,    0,    0, 1088, 1089,   67,   70, 1070,    0,
     1089,   72, 1089, 1074, 1071,   63,    0,   61, 1089, 1067,
      100,   71,   89,   69,  111,  115,   90,   72,   97,   73,
     1070,  151,  153,  150,  202,  173,  179,  255,  307,  188,
      167,  192, 1043,   86, 1089, 1075,   91, 1089, 1089,    0,
       87,  123,  216,   94, 1067, 1066, 1065,  169,  218,  228,
      175,  249,  195,  258, 1064,  223,  224,  246,  256,  260,
      270,  274,  290,  132,  288,  297,  265,  305,  316,  328,
     1063,  302,  310,  320,  350,  330,  144,  337,  345,  343,
     1062,  356,  366,  364,  313,  372,  370,  273,  375,  379,

      380,  385,  383,  393,  234,  398,  407,  410,  405,  402,
      419,  423,  418,  438,  439,  443,  436,  444,  427, 1089,
        0,  446, 1060, 1059, 1059, 1058,  452, 1057, 1056, 1055,
     1054, 1053,  456,  459,  462,  472,  468,  465,  464,  469,
      490,  488,  478,  494, 1052,  471,  498,  463,  495,  502,
     1051,  503,  516,  521,  524,  511,  525,  533,  537,  534,
     1050,  536,  538, 1049,  550,  509,  544,  558,  542,  541,
      562,  554,  572,  578,  561,  576, 1048,  577, 1047,  586,
      584,   67, 1046,  581,  598,  597,  602,  603,  600,  605,
      607,  609, 1045,  612,  623,  619,  614,  631,  629,  630,

      640,  637, 1039,  627,  649,  652,  658,  656, 1028,  665,
     1021,  661,  663,  671, 1020,  676,  664,  666,  672,  683,
     1019, 1018, 1017, 1015, 1014,  686,  691,  695,  693, 1013,
      697,  700, 1012,  688,  715,  722,  727,  704,  702, 1011,
      725, 1008, 1005,   83,  739, 1004,  732,  737,  741, 1002,
      729,  744,  746,  747,  755,  753, 1001,  765,  996,  995,
      767,  993,  771,  761,  992,  990,  749,  773,  770,  774,
      957,  779,  938,  792,  933,  788,  797,  890,  852,  795,
      847,  833,  708,  798,  800,  806,  681,  635,  812,  813,
      818,  546,  817,  821,  519,  820,  507,  834,  431,  825,

      783,  430,  837,  842,  389,  831,  382,  849,  352,  854,
      333,  329,  860,  861,  859,  864,  873,  868,  876,  327,
      298,  882,  884,  856,  895,  279,  878,  892,  277,  257,
      886,  901,  906,  908,  245,  907,  909,  911,  903,  915,
      922,  926,  242,  919,  925,  240,  927,  943,  935,  932,
      950,  955,  212,  947,  966,  939,  204,  967,  198,  971,
      181,  176,  170,  973,  148,  970,  127,  976,  960,  112,
      979,  980,  987,  106,   86,   85, 1089, 1038, 1043,   78,
     1045, 1050, 1052
    } ;

static yyconst flex_int16_t yy_def[384] =
    {   0,
      377,    1,    1,    1,  377,  377,  377,  377,  377,  378,
      377,  379,  377,  377,  377,  377,  380,  377,  377,  377,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,   38,  377,  377,  378,  379,  377,  377,  382,
      377,  377,  377,  377,  383,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  377,
      382,  377,  377,  377,  383,  383,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,    0,  377,  377,  377,
      377,  377,  377
    } ;

static yyconst flex_int16_t yy_nxt[1158] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   11,   12,   13,
       11,   14,   15,   16,   17,   18,   19,   20,    6,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   31,   37,   38,   39,   40,
       41,   42,   31,   31,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       37,   43,   39,   40,   41,   42,   31,   31,   44,   44,
       44,   44,   44,   44,   48,   52,   53,   45,   45,   57,
       49,   57,   55,   57,   57,   57,   54,   44,   44,   44,
       63,   79,   70,   48,   64,   57,   71,   57,   57,   49,

       51,   57,   57,  244,  123,  123,   82,  124,   66,   57,
       54,   54,   57,  291,   65,   63,   79,   70,   57,   64,
       58,   71,   67,   57,   57,   68,   78,   57,   69,   80,
       59,   82,   60,   66,   81,   54,  122,   61,   65,   57,
       62,   72,   75,   73,   57,   58,   54,   67,   76,   68,
       78,   77,   69,   74,   80,   59,   57,   60,   81,  146,
       57,   61,   57,   57,   62,   57,   72,   75,   73,   88,
       83,   54,   86,   76,   84,   77,  162,   74,   85,   57,
       87,   57,   57,   89,  146,   57,  116,   57,   57,   90,
      117,   57,   96,   57,   88,   83,  131,   86,   98,   84,

       57,  162,  127,   85,   57,   87,   99,   57,   89,   97,
       57,  116,  100,   90,   57,  117,   57,   96,  118,  119,
      113,  131,  114,   98,   57,  115,   91,  127,   52,   53,
       57,   99,  133,   97,   92,   57,   57,  100,   93,   54,
       57,   94,   95,  118,  119,  113,   57,  114,  128,  115,
      129,   91,   57,  182,   57,  137,  133,   57,   57,   92,
      136,   57,   93,  138,   54,   94,   95,   57,   57,   57,
       57,  130,   57,  128,  132,  129,  101,   57,  102,  139,
      137,  103,   57,  134,  136,   57,   57,  138,  104,   57,
      141,   57,  140,  105,  106,  130,  135,  142,  149,  132,

       57,  101,   57,  102,  139,  173,  103,  143,  134,   57,
       57,  144,  145,  104,   57,  141,  140,   57,  106,   57,
      135,  142,   57,  149,  147,   57,  107,  148,   57,  156,
      173,  143,   57,  108,  109,  144,  169,  145,  150,   57,
       57,   57,   57,  110,  158,   57,  111,  157,  147,   57,
      112,  107,  148,  151,  156,   57,  152,   57,  108,  109,
      153,  169,   57,  150,   57,  154,  155,  110,   57,  158,
      111,  157,  161,  165,  112,  163,   57,  151,   57,  159,
      152,  160,   57,  164,   57,  153,  166,   57,  167,  154,
      155,   57,   57,  171,   57,   57,  161,   57,  165,  163,

      174,   57,  168,  172,  159,   57,  160,  164,  170,  175,
       57,  166,  177,  167,   57,  178,  180,   57,  171,   57,
      176,  187,   57,  179,  181,  174,  168,  184,  172,  183,
       57,   57,  170,  185,  175,   57,  186,  177,  190,   57,
      178,  180,   57,   57,  176,  191,  187,  179,   57,  181,
       57,   57,  184,  188,  183,   57,   57,  189,  185,  122,
      192,  186,  193,  190,   57,  198,  194,  197,   57,   54,
      191,   57,  196,  195,   57,   57,   57,   57,  188,  200,
       57,   57,  189,   57,   57,  192,  201,  193,  199,  198,
       57,  194,  197,  214,   54,  203,  196,  205,  195,  204,

       57,  206,   57,  202,  200,  207,   57,   57,  212,  209,
       57,  201,  199,  208,   57,   57,  210,  211,  214,   57,
      203,   57,  205,   57,  204,  206,  215,  202,   57,  207,
      217,   57,  212,   57,  209,  213,   57,   57,  208,  218,
      210,  216,  211,  222,  219,   57,   57,  220,   57,   57,
       57,  215,  230,   57,   57,  217,   57,  221,   57,  213,
      225,  226,   57,  223,  218,  216,   57,  231,  222,  219,
       57,  224,  220,   57,   57,  227,  230,  228,  233,  234,
      229,  232,  221,  235,   57,  225,  226,  223,   57,   57,
       57,  239,  231,   57,  236,  224,   57,  237,   57,  227,

      241,  228,  233,  234,  238,  229,  232,  243,  235,   57,
       57,  245,   57,  240,   57,   57,  239,   57,  236,   57,
      247,   57,  237,  250,   57,  241,   57,  242,  253,  238,
      246,   57,  243,  249,  248,   57,  245,  240,  251,   57,
      252,   57,   57,   57,  254,  247,  257,   57,  250,   57,
      258,  242,   57,  253,  264,  246,  256,  259,  249,  248,
      263,   57,  255,  251,   57,  252,  261,  260,   57,  254,
       57,  257,  262,   57,  258,   57,   57,   57,   57,  264,
      256,  267,  259,   57,   57,  263,  255,  265,   57,  266,
      261,  260,  269,   57,  268,   57,  274,  262,   57,  270,

       57,  271,  275,   57,  272,   57,  267,   57,  276,   57,
      273,  265,   57,  266,   57,  284,   57,  269,  268,  277,
       57,  274,  289,  270,  278,  271,  275,   57,  279,  272,
      281,  280,  276,  282,   57,  273,  283,   57,  285,   57,
      284,   57,  288,  277,   57,  286,  290,  289,  278,   57,
      287,   57,  279,   57,  281,  280,   57,  282,   57,   57,
      283,   57,  292,  285,  295,   57,  288,   57,  296,  293,
      286,  290,  299,   57,  294,  287,  297,   57,  300,   57,
      301,  306,   57,   57,  298,   57,   57,  292,  302,  295,
      303,   57,  296,  293,  304,   57,  307,  299,  294,  305,

       57,  297,  308,  300,   57,  301,  306,   57,  298,   57,
       57,  309,   57,  302,  315,  303,  327,  311,   57,  304,
      310,  307,  317,  305,   57,   57,  312,  308,  313,   57,
       57,  319,   57,   57,  314,  309,  316,   57,  318,  315,
      323,  327,  311,   57,  310,   57,   57,  317,  321,   57,
      312,  320,  324,  313,   57,  322,  319,  325,  314,   57,
      316,   57,  326,  318,   57,  323,   57,  328,   57,  330,
      331,   57,   57,   57,  329,  320,   57,  324,  342,  322,
       57,  332,  325,  333,  334,   57,  326,  338,   57,  335,
       57,  336,  328,  330,   57,  331,   57,  339,   57,  329,

      337,  340,   57,  342,   57,  341,  332,   57,  333,  334,
      344,  345,  338,   57,  335,   57,  336,  343,   57,   57,
       57,   57,  339,   57,  346,  337,  340,   57,  348,  349,
      341,   57,  353,  347,   57,  344,  345,   57,   57,   57,
      350,  351,  343,  352,   57,   57,  354,   57,  346,  356,
       57,   57,  359,  348,  349,   57,  357,  353,  347,   57,
      355,  367,   57,  358,  362,  350,  351,   57,  352,   57,
      360,  354,   57,  361,  356,  363,  364,  359,   57,   57,
      357,  365,   57,   57,  355,   57,  367,  358,   57,  362,
      369,   57,   57,  366,  368,  360,  370,  361,  373,   57,

      363,  364,   57,  371,   57,   57,  365,   57,   57,  372,
      376,  374,  375,   57,   57,  369,   57,   57,  366,  368,
       57,  370,  373,   57,   57,   57,   57,   57,  371,   57,
       57,   57,   57,   57,  372,  376,  374,  375,   46,   46,
       57,   46,   46,   47,   47,   47,   47,   47,   56,   56,
      121,   57,  121,  121,  121,  125,  125,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
      377,  126,  124,  124,   57,   57,   57,  377,   57,  126,
      120,   56,   57,   45,   51,   50,   45,  377,    5,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,

      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377
    } ;

static yyconst flex_int16_t yy_chk[1158] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    7,    7,
        7,    8,    8,    8,   12,   16,   16,   18,   18,  182,
       12,   24,  380,   22,   28,   30,   16,   44,   44,   44,
       22,   28,   24,   47,   22,  244,   24,  376,  375,   47,

       51,   23,   27,  182,   54,   54,   30,   54,   23,   29,
       51,   16,   21,  244,   22,   22,   28,   24,  374,   22,
       21,   24,   23,   25,  370,   23,   27,   26,   23,   29,
       21,   30,   21,   23,   29,   51,   52,   21,   22,  367,
       21,   25,   26,   25,   74,   21,   52,   23,   26,   23,
       27,   26,   23,   25,   29,   21,   87,   21,   29,   74,
      365,   21,   34,   32,   21,   33,   25,   26,   25,   34,
       32,   52,   33,   26,   32,   26,   87,   25,   32,   41,
       33,   58,  363,   34,   74,   36,   41,   61,  362,   34,
       41,   37,   36,  361,   34,   32,   61,   33,   37,   32,

       40,   87,   58,   32,   42,   33,   37,   63,   34,   36,
      359,   41,   37,   34,   35,   41,  357,   36,   42,   42,
       40,   61,   40,   37,  353,   40,   35,   58,   53,   53,
       59,   37,   63,   36,   35,   66,   67,   37,   35,   53,
       60,   35,   35,   42,   42,   40,  105,   40,   59,   40,
       60,   35,  346,  105,  343,   67,   63,  335,   68,   35,
       66,   62,   35,   67,   53,   35,   35,   38,   69,  330,
       64,   60,   70,   59,   62,   60,   38,   77,   38,   68,
       67,   38,   71,   64,   66,   98,   72,   67,   38,  329,
       70,  326,   69,   38,   38,   60,   64,   70,   77,   62,

       75,   38,   73,   38,   68,   98,   38,   71,   64,   76,
      321,   72,   73,   38,   82,   70,   69,   78,   38,   39,
       64,   70,   83,   77,   75,   95,   39,   76,   79,   82,
       98,   71,   84,   39,   39,   72,   95,   73,   78,  320,
       80,  312,   86,   39,   84,  311,   39,   83,   75,   88,
       39,   39,   76,   79,   82,   90,   79,   89,   39,   39,
       80,   95,   85,   78,  309,   80,   80,   39,   92,   84,
       39,   83,   86,   90,   39,   88,   94,   79,   93,   85,
       79,   85,   97,   89,   96,   80,   92,   99,   93,   80,
       80,  100,  101,   97,  307,  103,   86,  102,   90,   88,

       99,  305,   94,   97,   85,  104,   85,   89,   96,  100,
      106,   92,  101,   93,  110,  102,  103,  109,   97,  107,
      100,  110,  108,  102,  104,   99,   94,  107,   97,  106,
      113,  111,   96,  108,  100,  112,  109,  101,  113,  119,
      102,  103,  302,  299,  100,  113,  110,  102,  117,  104,
      114,  115,  107,  111,  106,  116,  118,  112,  108,  122,
      114,  109,  115,  113,  127,  119,  115,  118,  133,  122,
      113,  134,  117,  116,  135,  148,  139,  138,  111,  133,
      137,  140,  112,  146,  136,  114,  134,  115,  127,  119,
      143,  115,  118,  148,  122,  136,  117,  138,  116,  137,

      142,  139,  141,  135,  133,  140,  144,  149,  146,  142,
      147,  134,  127,  141,  150,  152,  143,  144,  148,  297,
      136,  166,  138,  156,  137,  139,  149,  135,  153,  140,
      152,  295,  146,  154,  142,  147,  155,  157,  141,  153,
      143,  150,  144,  156,  154,  158,  160,  155,  162,  159,
      163,  149,  166,  170,  169,  152,  167,  155,  292,  147,
      159,  160,  165,  157,  153,  150,  172,  167,  156,  154,
      168,  158,  155,  175,  171,  162,  166,  163,  169,  170,
      165,  168,  155,  171,  173,  159,  160,  157,  176,  178,
      174,  175,  167,  184,  172,  158,  181,  173,  180,  162,

      178,  163,  169,  170,  174,  165,  168,  181,  171,  186,
      185,  184,  189,  176,  187,  188,  175,  190,  172,  191,
      186,  192,  173,  189,  194,  178,  197,  180,  192,  174,
      185,  196,  181,  188,  187,  195,  184,  176,  190,  204,
      191,  199,  200,  198,  194,  186,  197,  288,  189,  202,
      197,  180,  201,  192,  204,  185,  196,  198,  188,  187,
      202,  205,  195,  190,  206,  191,  200,  199,  208,  194,
      207,  197,  201,  212,  197,  213,  217,  210,  218,  204,
      196,  207,  198,  214,  219,  202,  195,  205,  216,  206,
      200,  199,  210,  287,  208,  220,  217,  201,  226,  212,

      234,  213,  218,  227,  214,  229,  207,  228,  219,  231,
      216,  205,  232,  206,  239,  234,  238,  210,  208,  220,
      283,  217,  239,  212,  226,  213,  218,  235,  227,  214,
      229,  228,  219,  231,  236,  216,  232,  241,  235,  237,
      234,  251,  238,  220,  247,  236,  241,  239,  226,  248,
      237,  245,  227,  249,  229,  228,  252,  231,  253,  254,
      232,  267,  245,  235,  249,  256,  238,  255,  251,  247,
      236,  241,  254,  264,  248,  237,  252,  258,  255,  261,
      256,  267,  269,  263,  253,  268,  270,  245,  258,  249,
      261,  272,  251,  247,  263,  301,  268,  254,  248,  264,

      276,  252,  269,  255,  274,  256,  267,  280,  253,  277,
      284,  270,  285,  258,  280,  261,  301,  274,  286,  263,
      272,  268,  285,  264,  289,  290,  276,  269,  277,  293,
      291,  289,  296,  294,  277,  270,  284,  300,  286,  280,
      294,  301,  274,  306,  272,  282,  298,  285,  291,  303,
      276,  290,  296,  277,  304,  293,  289,  298,  277,  281,
      284,  308,  300,  286,  279,  294,  310,  303,  324,  306,
      308,  315,  313,  314,  304,  290,  316,  296,  324,  293,
      318,  310,  298,  313,  314,  317,  300,  318,  319,  315,
      327,  316,  303,  306,  322,  308,  323,  319,  331,  304,

      317,  322,  278,  324,  328,  323,  310,  325,  313,  314,
      327,  328,  318,  332,  315,  339,  316,  325,  333,  336,
      334,  337,  319,  338,  331,  317,  322,  340,  333,  334,
      323,  344,  339,  332,  341,  327,  328,  345,  342,  347,
      336,  337,  325,  338,  350,  275,  340,  349,  331,  342,
      273,  356,  347,  333,  334,  348,  344,  339,  332,  354,
      341,  356,  351,  345,  350,  336,  337,  352,  338,  271,
      348,  340,  369,  349,  342,  351,  352,  347,  355,  358,
      344,  354,  366,  360,  341,  364,  356,  345,  368,  350,
      360,  371,  372,  355,  358,  348,  364,  349,  369,  373,

      351,  352,  266,  366,  265,  262,  354,  260,  259,  368,
      373,  371,  372,  257,  250,  360,  246,  243,  355,  358,
      242,  364,  369,  240,  233,  230,  225,  224,  366,  223,
      222,  221,  215,  211,  368,  373,  371,  372,  378,  378,
      209,  378,  378,  379,  379,  379,  379,  379,  381,  381,
      382,  203,  382,  382,  382,  383,  383,  193,  183,  179,
      177,  164,  161,  151,  145,  132,  131,  130,  129,  128,
      126,  125,  124,  123,   91,   81,   65,   57,   56,   55,
       46,   43,   31,   20,   15,   14,    9,    5,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,

      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[102] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int postgres_flex_debug;
int postgres_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *postgrestext;
#line 1 "postgres_parser.l"
/*
 * SQL lexer file for lex/flex defining basic tokens used in the oracle parser
 *
 */
/*******************************************************************************
 * options section 
 ******************************************************************************/
/* set lexer options */
/* includes */
#line 19 "postgres_parser.l"
#include "common.h"
#include "log/logger.h"
#include "mem_manager/mem_mgr.h"
#include "model/expression/expression.h"
#include "model/list/list.h"
#include "model/node/nodetype.h"
#include "parser/parse_internal_postgres.h"
#include "postgres_parser.tab.h"

#undef free

#define TOKSELF() { \
	TRACE_LOG("Lexed TOKENSELF <%c> with VALUE <%c>", postgrestext[0], postgrestext[0]); \
	postgreslval.stringVal = strdup(postgrestext); \
	return postgrestext[0]; \
	}
#define TOK(name) { \
	TRACE_LOG("Lexed TOKEN <%s> with VALUE <%s>", #name, postgrestext); \
 	postgreslval.stringVal = strdup(postgrestext); \
 	return name; \
 	}
#define DOWNCASE_TOK(name) { \
	TRACE_LOG("Lexed TOKEN <%s> with VALUE <%s>", #name, postgrestext); \
	char *result = strdup(postgrestext); \
	postgreslval.stringVal = result; \
	for(; *result != '\0'; (*(result) = tolower(*result)), result++); \
	return name; \
	}
#define TOKSAVE(name,field,function) { \
	TRACE_LOG("Lexed TOKEN <%s> of TYPE <%s>",  #name, #field); \
	postgreslval.field = function(postgrestext); \
	return name; \
	}
/********************************************************************
 * lexer states 
 */

/********************************************************************
 * predefined regular expressions 
 */
/* whitespace */
/* numbers */
/* names (e.g., tables, attributes) */
/* operators */
/* comparisonOps	['!'|'<'|'>'|'=']{1,2} */ 
/*shiftsOps		["<<"|">>"] */
/*******************************************************************************
 * Token definitions and actions 
 ******************************************************************************/
#line 935 "postgres_parser.lex.c"

#define INITIAL 0
#define SQL 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int postgreslex_destroy (void );

int postgresget_debug (void );

void postgresset_debug (int debug_flag  );

YY_EXTRA_TYPE postgresget_extra (void );

void postgresset_extra (YY_EXTRA_TYPE user_defined  );

FILE *postgresget_in (void );

void postgresset_in  (FILE * in_str  );

FILE *postgresget_out (void );

void postgresset_out  (FILE * out_str  );

yy_size_t postgresget_leng (void );

char *postgresget_text (void );

int postgresget_lineno (void );

void postgresset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int postgreswrap (void );
#else
extern int postgreswrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( postgrestext, postgresleng, 1, postgresout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( postgresin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( postgresin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, postgresin))==0 && ferror(postgresin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(postgresin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int postgreslex (void);

#define YY_DECL int postgreslex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after postgrestext and postgresleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 96 "postgres_parser.l"


	/* ignore all whitespace */
#line 1122 "postgres_parser.lex.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! postgresin )
			postgresin = stdin;

		if ( ! postgresout )
			postgresout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			postgresensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				postgres_create_buffer(postgresin,YY_BUF_SIZE );
		}

		postgres_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of postgrestext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 378 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1089 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < postgresleng; ++yyl )
				if ( postgrestext[yyl] == '\n' )
					   
    postgreslineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 99 "postgres_parser.l"
{ TRACE_LOG("Lexed whitespace <%s>", postgrestext); /* ignore it */ }
	YY_BREAK
/* literal keyword tokens */
case 2:
YY_RULE_SETUP
#line 102 "postgres_parser.l"
TOK(SELECT)
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 103 "postgres_parser.l"
TOK(INSERT)
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 104 "postgres_parser.l"
TOK(UPDATE)
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 105 "postgres_parser.l"
TOK(DELETE)
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 106 "postgres_parser.l"
TOK(SET)
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 107 "postgres_parser.l"
TOK(PROVENANCE)
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 108 "postgres_parser.l"
TOK(OF)
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 109 "postgres_parser.l"
TOK(FROM)
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 110 "postgres_parser.l"
TOK(AS)
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 111 "postgres_parser.l"
TOK(WHERE)
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 112 "postgres_parser.l"
TOK(DISTINCT)
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 113 "postgres_parser.l"
TOK(ON)
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 114 "postgres_parser.l"
TOK(STARALL)
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 115 "postgres_parser.l"
TOK(ALL)
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 116 "postgres_parser.l"
TOK(AND)
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 117 "postgres_parser.l"
TOK(OR)
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 118 "postgres_parser.l"
TOK(AMMSC)
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 119 "postgres_parser.l"
TOK(AMMSC)
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 120 "postgres_parser.l"
TOK(AMMSC)
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 121 "postgres_parser.l"
TOK(AMMSC)
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 122 "postgres_parser.l"
TOK(AMMSC)
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 123 "postgres_parser.l"
TOK(ANY)
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 124 "postgres_parser.l"
TOK(SOME)
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 125 "postgres_parser.l"
TOK(BETWEEN)
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 126 "postgres_parser.l"
TOK(BY)
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 127 "postgres_parser.l"
TOK(UPDATE)
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 128 "postgres_parser.l"
TOK(DELETE)
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 129 "postgres_parser.l"
TOK(IS)
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 130 "postgres_parser.l"
TOK(NULLVAL)
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 131 "postgres_parser.l"
TOK(UNION)
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 132 "postgres_parser.l"
TOK(INTERSECT)
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 133 "postgres_parser.l"
TOK(MINUS)
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 134 "postgres_parser.l"
TOK(JOIN)
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 135 "postgres_parser.l"
TOK(LEFT)
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 136 "postgres_parser.l"
TOK(RIGHT)
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 137 "postgres_parser.l"
TOK(OUTER)
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 138 "postgres_parser.l"
TOK(INNER)
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 139 "postgres_parser.l"
TOK(NATURAL)
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 140 "postgres_parser.l"
TOK(USING)
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 141 "postgres_parser.l"
TOK(CROSS)
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 142 "postgres_parser.l"
TOK(INTO)
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 143 "postgres_parser.l"
TOK(VALUES)
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 144 "postgres_parser.l"
TOK(IN)
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 145 "postgres_parser.l"
TOK(EXISTS)
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 146 "postgres_parser.l"
TOK(LIKE)
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 147 "postgres_parser.l"
TOK(GROUP)
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 148 "postgres_parser.l"
TOK(NOT)
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 149 "postgres_parser.l"
TOK(HAVING)
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 150 "postgres_parser.l"
TOK(LIMIT)
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 151 "postgres_parser.l"
TOK(ORDER)
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 152 "postgres_parser.l"
TOK(BEGIN_TRANS)
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 153 "postgres_parser.l"
TOK(COMMIT_TRANS)
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 154 "postgres_parser.l"
TOK(ROLLBACK_TRANS)
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 155 "postgres_parser.l"
TOK(ROLLBACK_TRANS)
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 156 "postgres_parser.l"
TOK(BASERELATION)
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 157 "postgres_parser.l"
TOK(SCN)
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 158 "postgres_parser.l"
TOK(TIMESTAMP)
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 159 "postgres_parser.l"
TOK(TYPE)
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 160 "postgres_parser.l"
TOK(TRANSACTION)
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 161 "postgres_parser.l"
TOK(WITH)
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 162 "postgres_parser.l"
TOK(HAS)
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 163 "postgres_parser.l"
TOK(CASE)
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 164 "postgres_parser.l"
TOK(WHEN)
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 165 "postgres_parser.l"
TOK(THEN)
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 166 "postgres_parser.l"
TOK(END)
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 167 "postgres_parser.l"
TOK(ELSE)
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 168 "postgres_parser.l"
TOK(OVER_TOK)
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 169 "postgres_parser.l"
TOK(PARTITION)
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 170 "postgres_parser.l"
TOK(ROWS)
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 171 "postgres_parser.l"
TOK(RANGE)
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 172 "postgres_parser.l"
TOK(UNBOUNDED)
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 173 "postgres_parser.l"
TOK(PRECEDING)
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 174 "postgres_parser.l"
TOK(CURRENT)
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 175 "postgres_parser.l"
TOK(ROW)
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 176 "postgres_parser.l"
TOK(FOLLOWING)
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 177 "postgres_parser.l"
TOK(TABLE)
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 178 "postgres_parser.l"
TOK(ONLY)
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 179 "postgres_parser.l"
TOK(UPDATED)
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 180 "postgres_parser.l"
TOK(SHOW)
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 181 "postgres_parser.l"
TOK(INTERMEDIATE)
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 182 "postgres_parser.l"
TOK(USE)
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 183 "postgres_parser.l"
TOK(ASC)
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 184 "postgres_parser.l"
TOK(DESC)
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 185 "postgres_parser.l"
TOK(NULLS)
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 186 "postgres_parser.l"
TOK(FIRST)
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 187 "postgres_parser.l"
TOK(LAST)
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 188 "postgres_parser.l"
TOK(TUPLE)
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 189 "postgres_parser.l"
TOK(VERSIONS)
	YY_BREAK
/* names */
case 90:
YY_RULE_SETUP
#line 192 "postgres_parser.l"
DOWNCASE_TOK(identifier)
	YY_BREAK
case 91:
/* rule 91 can match eol */
YY_RULE_SETUP
#line 193 "postgres_parser.l"
{ 		
		postgreslval.stringVal = MALLOC(strlen(postgrestext) - 1);
		memcpy(postgreslval.stringVal, postgrestext + 1, strlen(postgrestext) - 2);
		postgreslval.stringVal[strlen(postgrestext) - 2] = '\0';
		TRACE_LOG("Lexed TOKEN <quotedIdentifier> with VALUE <%s>", postgrestext);
		return identifier;
	}	
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 201 "postgres_parser.l"
{
		postgreslval.stringVal = MALLOC(strlen(postgrestext));
		memcpy(postgreslval.stringVal, postgrestext + 1, strlen(postgrestext) - 1);
		postgreslval.stringVal[strlen(postgrestext) - 1] = '\0';
		TRACE_LOG("Lexed TOKEN <parameter> with VALUE <:%s>", postgrestext);
		return parameter;
	}
	YY_BREAK
/* punctuation */
case 93:
YY_RULE_SETUP
#line 210 "postgres_parser.l"
TOKSELF()
	YY_BREAK
/* operators */
case 94:
YY_RULE_SETUP
#line 213 "postgres_parser.l"
TOK(comparisonOps)
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 214 "postgres_parser.l"
TOKSELF()
	YY_BREAK
/* numbers */
case 96:
YY_RULE_SETUP
#line 219 "postgres_parser.l"
TOKSAVE(intConst,intVal,atoi)
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 220 "postgres_parser.l"
TOKSAVE(floatConst,floatVal,atof)
	YY_BREAK
/* strings */
case 98:
YY_RULE_SETUP
#line 223 "postgres_parser.l"
{
		postgreslval.stringVal = MALLOC(strlen(postgrestext) - 1);
		memcpy(postgreslval.stringVal, postgrestext + 1, strlen(postgrestext) - 2);
		postgreslval.stringVal[strlen(postgrestext) - 2] = '\0';
		TRACE_LOG("Lexed TOKEN <stringConst> with VALUE <%s>", postgrestext);
		return stringConst;
	}
	YY_BREAK
case 99:
*yy_cp = (yy_hold_char); /* undo effects of setting up postgrestext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up postgrestext again */
YY_RULE_SETUP
#line 232 "postgres_parser.l"
{postgreserror("Unterminated string"); }
	YY_BREAK
/* failure - no token matched */
case 100:
YY_RULE_SETUP
#line 235 "postgres_parser.l"
{ postgreserror("Unknown symbol"); }	/* random non-SQL text */
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 237 "postgres_parser.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1750 "postgres_parser.lex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SQL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed postgresin at a new source and called
			 * postgreslex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = postgresin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( postgreswrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * postgrestext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of postgreslex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					postgresrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			postgresrestart(postgresin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) postgresrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 378 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 378 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 377);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up postgrestext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --postgreslineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					postgresrestart(postgresin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( postgreswrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve postgrestext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    postgreslineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void postgresrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        postgresensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            postgres_create_buffer(postgresin,YY_BUF_SIZE );
	}

	postgres_init_buffer(YY_CURRENT_BUFFER,input_file );
	postgres_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void postgres_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		postgrespop_buffer_state();
	 *		postgrespush_buffer_state(new_buffer);
     */
	postgresensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	postgres_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (postgreswrap()) processing, but the only time this flag
	 * is looked at is after postgreswrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void postgres_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	postgresin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE postgres_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) postgresalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in postgres_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) postgresalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in postgres_create_buffer()" );

	b->yy_is_our_buffer = 1;

	postgres_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with postgres_create_buffer()
 * 
 */
    void postgres_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		postgresfree((void *) b->yy_ch_buf  );

	postgresfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a postgresrestart() or at EOF.
 */
    static void postgres_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	postgres_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then postgres_init_buffer was _probably_
     * called from postgresrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void postgres_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		postgres_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void postgrespush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	postgresensure_buffer_stack();

	/* This block is copied from postgres_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from postgres_switch_to_buffer. */
	postgres_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void postgrespop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	postgres_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		postgres_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void postgresensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)postgresalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in postgresensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)postgresrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in postgresensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE postgres_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) postgresalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in postgres_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	postgres_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to postgreslex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       postgres_scan_bytes() instead.
 */
YY_BUFFER_STATE postgres_scan_string (yyconst char * yystr )
{
    
	return postgres_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to postgreslex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE postgres_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) postgresalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in postgres_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = postgres_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in postgres_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up postgrestext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		postgrestext[postgresleng] = (yy_hold_char); \
		(yy_c_buf_p) = postgrestext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		postgresleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int postgresget_lineno  (void)
{
        
    return postgreslineno;
}

/** Get the input stream.
 * 
 */
FILE *postgresget_in  (void)
{
        return postgresin;
}

/** Get the output stream.
 * 
 */
FILE *postgresget_out  (void)
{
        return postgresout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t postgresget_leng  (void)
{
        return postgresleng;
}

/** Get the current token.
 * 
 */

char *postgresget_text  (void)
{
        return postgrestext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void postgresset_lineno (int  line_number )
{
    
    postgreslineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see postgres_switch_to_buffer
 */
void postgresset_in (FILE *  in_str )
{
        postgresin = in_str ;
}

void postgresset_out (FILE *  out_str )
{
        postgresout = out_str ;
}

int postgresget_debug  (void)
{
        return postgres_flex_debug;
}

void postgresset_debug (int  bdebug )
{
        postgres_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from postgreslex_destroy(), so don't allocate here.
     */

    /* We do not touch postgreslineno unless the option is enabled. */
    postgreslineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    postgresin = stdin;
    postgresout = stdout;
#else
    postgresin = (FILE *) 0;
    postgresout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * postgreslex_init()
     */
    return 0;
}

/* postgreslex_destroy is for both reentrant and non-reentrant scanners. */
int postgreslex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		postgres_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		postgrespop_buffer_state();
	}

	/* Destroy the stack itself. */
	postgresfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * postgreslex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *postgresalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *postgresrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void postgresfree (void * ptr )
{
	free( (char *) ptr );	/* see postgresrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 237 "postgres_parser.l"



/*******************************************************************************
 * Literal C code to include
 ******************************************************************************/

/* use logging framework in the future */
void postgreserror(char *s)
{
	ERROR_LOG("%s at %s\n", s, postgrestext);
}

void postgresSetupStringInput(char *input)
{
	postgres_scan_string(input);
}

