#line 2 "sql_parser.lex.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 91
#define YY_END_OF_BUFFER 92
static yyconst short int yy_acclist[482] =
    {   0,
       92,   90,   91,    1,   90,   91,    1,   91,   85,   90,
       91,   90,   91,   85,   90,   91,   90,   91,   83,   90,
       91,   85,   90,   91,   83,   90,   91,   86,   87,   90,
       91,   90,   91,   84,   90,   91,   84,   90,   91,   84,
       90,   91,   80,   90,   91,   80,   90,   91,   80,   90,
       91,   80,   90,   91,   80,   90,   91,   80,   90,   91,
       80,   90,   91,   80,   90,   91,   80,   90,   91,   80,
       90,   91,   80,   90,   91,   80,   90,   91,   80,   90,
       91,   80,   90,   91,   80,   90,   91,   80,   90,   91,
       80,   90,   91,   80,   90,   91,   80,   90,   91,   80,

       90,   91,   80,   90,   91,   80,   90,   91,    1,   84,
       89,   88,    1,   87,   87,   86,   87,   82,   80,   80,
       80,   80,   10,   80,   80,   80,   80,   26,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   44,   80,   29,   80,   80,   80,   80,   80,
       80,   80,   80,   80,    8,   80,   13,   80,   17,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   81,    1,   87,   87,   82,   80,   15,
       80,   16,   80,   23,   80,   18,   80,   80,   80,   80,

       80,   80,   80,   80,   80,   80,   80,   80,   66,   80,
       80,   80,   80,   80,   62,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   20,   80,   19,   80,   80,   47,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   75,   80,   57,   80,   80,    6,   80,   80,
       80,   21,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   63,
       80,   80,   80,   80,   80,   80,   80,   67,   80,   80,
       80,    9,   80,   80,   80,   80,   80,   80,   42,   80,
       34,   80,   35,   80,   46,   80,   80,   80,   80,   30,

       80,   78,   80,   80,   80,   68,   80,   80,   80,   80,
       80,   80,   80,   70,   80,   80,   24,   80,   80,   80,
       65,   80,   80,   80,   59,   80,   80,   80,   80,   80,
       80,   64,   80,   80,   61,   80,   55,   80,   80,   52,
       80,   80,   80,   22,   80,   41,   80,   80,   80,   80,
       80,   80,   48,   80,   80,   38,   80,   80,   80,   50,
       80,   33,   80,   80,   51,   80,   37,   80,   80,   80,
       80,   71,   80,   36,   80,   80,   80,   80,   77,   80,
       80,   80,   80,   31,   80,   80,   40,   80,   80,   11,
       80,   80,   80,   53,   80,   80,    5,   28,   80,   80,

       45,   80,   80,   49,   80,    3,   80,   80,   80,   80,
       80,   80,   80,    2,   80,   14,   80,   80,   80,   80,
        4,   27,   80,   43,   80,   80,   25,   80,   74,   80,
       80,   80,   80,   39,   80,   80,   80,   80,   80,   80,
       80,   80,   79,   80,   80,   12,   80,   80,   80,   80,
       80,   80,   54,   80,   80,   80,   80,   80,   76,   80,
       32,   80,   69,   80,   73,   80,   80,   58,   80,   80,
       72,   80,   80,    7,   80,   80,   80,   60,   80,   56,
       80
    } ;

static yyconst short int yy_accept[345] =
    {   0,
        1,    1,    1,    1,    1,    2,    4,    7,    9,   12,
       14,   17,   19,   22,   25,   28,   32,   34,   37,   40,
       43,   46,   49,   52,   55,   58,   61,   64,   67,   70,
       73,   76,   79,   82,   85,   88,   91,   94,   97,  100,
      103,  106,  109,  110,  111,  111,  111,  112,  113,  114,
      115,  116,  118,  118,  119,  120,  120,  121,  122,  123,
      125,  126,  127,  128,  130,  131,  132,  133,  134,  135,
      136,  137,  138,  139,  140,  141,  142,  143,  145,  147,
      148,  149,  150,  151,  152,  153,  154,  155,  157,  159,
      161,  162,  163,  164,  165,  166,  167,  168,  169,  170,

      171,  172,  173,  174,  175,  176,  177,  178,  179,  180,
      181,  182,  183,  184,  185,  186,  187,  187,  188,  189,
      189,  190,  192,  194,  196,  198,  199,  200,  201,  202,
      203,  204,  205,  206,  207,  208,  209,  211,  212,  213,
      214,  215,  217,  218,  219,  220,  221,  222,  223,  224,
      225,  227,  229,  230,  232,  233,  234,  235,  236,  237,
      238,  239,  240,  241,  242,  243,  245,  247,  248,  250,
      251,  252,  254,  255,  256,  257,  258,  259,  260,  261,
      262,  263,  264,  265,  266,  267,  268,  269,  270,  272,
      273,  274,  275,  276,  277,  278,  280,  281,  282,  284,

      285,  286,  287,  288,  289,  291,  293,  295,  297,  298,
      299,  300,  302,  304,  305,  306,  308,  309,  310,  311,
      312,  313,  314,  316,  317,  319,  320,  321,  323,  324,
      325,  327,  328,  329,  330,  331,  332,  334,  335,  337,
      339,  340,  342,  343,  344,  346,  348,  349,  350,  351,
      352,  353,  355,  356,  358,  359,  360,  362,  364,  365,
      367,  369,  370,  371,  372,  374,  376,  377,  378,  379,
      381,  382,  383,  384,  386,  387,  389,  390,  392,  393,
      394,  396,  397,  400,  401,  403,  404,  406,  408,  409,
      410,  411,  412,  413,  414,  416,  418,  419,  420,  421,

      424,  426,  427,  429,  431,  432,  433,  434,  436,  437,
      438,  439,  440,  441,  442,  443,  445,  446,  448,  449,
      450,  451,  452,  453,  455,  456,  457,  458,  459,  461,
      463,  465,  467,  468,  470,  471,  473,  474,  476,  477,
      478,  480,  482,  482
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       10,    8,   11,   10,   12,   13,    8,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,   10,   16,
       17,   18,   19,    1,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   36,
        1,    1,    1,    8,   19,    1,   36,   36,   36,   36,

       45,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,    1,    8,    1,    8,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[46] =
    {   0,
        1,    1,    2,    2,    1,    3,    4,    1,    1,    1,
        1,    1,    4,    4,    1,    1,    1,    1,    4,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5
    } ;

static yyconst short int yy_base[350] =
    {   0,
        0,    0,    0,    0,  691,  692,   44,   47,  673,    0,
      692,   49,  692,  677,  674,   40,    0,   38,  692,  670,
       46,   48,   49,   47,   57,   44,   60,   78,   61,   67,
      673,   80,   82,   83,   93,   92,   94,  103,  111,  119,
      100,  108,  142,  692,  679,   73,  692,  692,    0,   95,
      127,  136,  147,  671,  670,  669,  134,  140,  143,  668,
      149,  150,  151,  667,  154,  157,  152,  156,  160,  161,
      163,  171,  167,  165,  166,  169,  170,  185,  666,  189,
      191,  196,  172,  192,  193,  194,  199,  665,  200,  197,
      201,  214,  206,  221,  208,  209,  216,  223,  226,  229,

      224,  235,  233,  236,  237,  239,  238,  249,  240,  251,
      253,  258,  255,  692,    0,  261,  663,  662,  662,  661,
      259,  660,  659,  658,  657,  263,  261,  265,  267,  268,
      270,  273,  275,  277,  279,  280,  656,  282,  284,  285,
      286,  655,  295,  289,  292,  297,  296,  301,  306,  309,
      654,  311,  312,  653,  314,  315,  319,  320,  321,  322,
      325,  323,  328,  326,  329,  333,  652,  342,  651,  343,
      335,  650,  337,  336,  349,  344,  350,  352,  357,  362,
      363,  365,  366,  367,  368,  371,  376,  374,  649,  372,
      375,  377,  380,  379,  382,  648,  384,  388,  647,  389,

      393,  398,  399,  400,  646,  645,  644,  643,  403,  406,
      404,  642,  641,  408,  412,  640,  415,  407,  414,  416,
      417,  426,  639,  433,  638,  419,  435,  637,  420,  438,
      636,  421,  439,  440,  441,  444,  635,  447,  634,  633,
      449,  632,  450,  451,  631,  630,  452,  453,  456,  457,
      462,  629,  465,  628,  467,  469,  627,  626,  468,  625,
      624,  470,  471,  479,  623,  622,  473,  474,  483,  621,
      484,  485,  486,  620,  487,  619,  488,  613,  489,  495,
      602,  490,  597,  502,  594,  497,  593,  592,  503,  504,
      505,  508,  517,  509,  591,  590,  519,  521,  525,  527,

      589,  529,  588,  587,  528,  531,  532,  586,  534,  533,
      538,  539,  540,  542,  546,  585,  543,  584,  547,  544,
      545,  548,  562,  583,  550,  549,  563,  552,  582,  581,
      580,  576,  566,  370,  574,  102,  575,   98,  578,  579,
       53,   52,  692,  612,  617,   58,  619,  624,  626
    } ;

static yyconst short int yy_def[350] =
    {   0,
      343,    1,    1,    1,  343,  343,  343,  343,  343,  344,
      343,  345,  343,  343,  343,  343,  346,  343,  343,  343,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  343,  343,  344,  345,  343,  343,  348,  343,
      343,  343,  343,  349,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  343,  348,  343,  343,  343,  349,  349,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,    0,  343,  343,  343,  343,  343,  343
    } ;

static yyconst short int yy_nxt[738] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   11,   12,   13,
       11,   14,   15,   16,   17,   18,   19,   20,    6,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   31,   37,   38,   39,   40,
       41,   42,   31,   31,   31,   43,   43,   43,   43,   43,
       43,   47,   51,   52,   44,   44,   56,   48,   56,   56,
       56,   56,   54,   53,   56,   56,   57,   62,   65,   56,
       69,   63,   56,   56,   70,   47,   58,   74,   59,   56,
       75,   48,   66,   60,   53,   67,   61,   71,   68,   72,
       56,   64,   56,   78,   56,   56,   76,   77,   79,   73,

       80,   83,   85,   81,   56,   56,   56,   82,   50,   84,
       56,   93,   56,   95,   56,   56,   86,   88,   53,  111,
       56,   96,   87,   56,   98,   89,   99,   97,   94,   90,
      103,   56,   91,   92,  112,  113,  100,  104,  105,   53,
      116,  101,  102,   43,   43,   43,   56,  106,   51,   52,
       53,  108,   56,  109,  107,   56,  110,  117,  117,   53,
      118,   56,   56,   56,   56,  123,   56,  121,   56,   56,
      122,   53,   56,   56,  125,   56,  127,   56,   56,   56,
       53,   56,   56,   56,   56,  132,  124,  126,  130,  128,
      134,  129,  133,  137,  138,  139,  131,   56,  135,  140,

      136,   56,  141,   56,   56,   56,   56,  142,   56,   56,
      143,   56,   56,   56,  151,  148,  147,  144,   56,  157,
       56,   56,  145,  146,  152,  149,   56,  150,   56,  155,
      156,  153,  154,   56,  164,   56,   56,  159,   56,  158,
      163,   56,  160,  171,  161,   56,  165,   56,   56,   56,
       56,   56,   56,  173,  162,  167,  168,  166,  176,  174,
      170,   56,  180,   56,  169,   56,  172,   56,  175,  178,
       56,   56,  177,   56,  116,   56,  179,   56,  181,   56,
       56,  183,   56,  182,   53,   56,  186,   56,  187,   56,
      189,   56,   56,  184,   56,  185,   56,   56,   56,  190,

      194,   56,  191,  196,   56,   53,  188,   56,   56,   56,
      192,  193,  202,   56,  198,  203,  199,  195,   56,  197,
      204,   56,  201,   56,   56,  200,   56,   56,  206,  208,
      205,   56,   56,   56,   56,   56,  209,   56,   56,  207,
       56,   56,  214,  215,  212,   56,  218,   56,   56,   56,
      210,  211,  221,  220,   56,   56,   56,  216,  213,  222,
      217,   56,   56,  219,   56,  224,  225,  227,  228,   56,
      223,  226,  229,  231,   56,   56,  230,   56,   56,   56,
       56,  234,   56,   56,   56,  232,   56,   56,   56,   56,
      233,   56,   56,  239,   56,  235,   56,  243,  237,  244,

       56,   56,  238,  247,  236,   56,  240,  241,  242,  249,
       56,   56,   56,  245,  246,   56,   56,  248,   56,   56,
       56,  251,  250,  252,   56,  253,   56,   56,   56,   56,
      263,   56,   56,   56,  254,  255,  256,  264,   56,  265,
      259,  257,  262,  258,  260,   56,  267,   56,  261,  269,
       56,   56,   56,   56,  268,  266,   56,  271,  270,   56,
      273,   56,   56,   56,   56,   56,  276,  277,   56,   56,
      278,  274,  279,  280,   56,  272,  283,   56,  275,   56,
       56,   56,   56,   56,  282,   56,   56,  290,  284,  281,
      287,   56,  294,  292,  285,   56,   56,   56,   56,   56,

       56,   56,   56,  286,  298,  288,  289,   56,  291,   56,
      300,  293,  295,  296,   56,   56,   56,   56,  299,  302,
       56,   56,  297,  305,  306,  301,  307,  303,  304,   56,
      312,   56,  309,   56,  308,  310,  311,   56,  313,   56,
       56,   56,  314,   56,   56,   56,   56,  315,  317,  316,
       56,   56,   56,  320,   56,   56,   56,   56,   56,   56,
       56,   56,   56,  319,   56,  322,  318,  321,  324,  327,
      323,  325,  329,  332,   56,   56,  335,  331,   56,  337,
      326,  328,  330,  333,  334,  336,   56,   56,   56,  338,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,

       56,   56,   56,   56,   56,   56,   56,  339,  340,   56,
      341,  342,   45,   45,   56,   45,   45,   46,   46,   46,
       46,   46,   55,   55,  115,   56,  115,  115,  115,  119,
      119,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,  343,  120,  118,  118,   56,   56,   56,
       56,  343,   56,  120,  114,   56,   44,   50,   49,   44,
      343,    5,  343,  343,  343,  343,  343,  343,  343,  343,

      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343
    } ;

static yyconst short int yy_chk[738] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    7,    7,    7,    8,    8,
        8,   12,   16,   16,   18,   18,   26,   12,   21,   24,
       22,   23,  346,   16,  342,  341,   21,   22,   23,   25,
       24,   22,   27,   29,   24,   46,   21,   26,   21,   30,
       26,   46,   23,   21,   16,   23,   21,   25,   23,   25,
       28,   22,   32,   29,   33,   34,   27,   28,   29,   25,

       30,   33,   34,   32,   36,   35,   37,   32,   50,   33,
      338,   36,   41,   37,  336,   38,   34,   35,   50,   41,
       42,   37,   34,   39,   38,   35,   38,   37,   36,   35,
       39,   40,   35,   35,   42,   42,   38,   39,   39,   50,
       51,   38,   38,   43,   43,   43,   57,   39,   52,   52,
       51,   40,   58,   40,   39,   59,   40,   53,   53,   52,
       53,   61,   62,   63,   67,   59,   65,   57,   68,   66,
       58,   51,   69,   70,   61,   71,   63,   74,   75,   73,
       52,   76,   77,   72,   83,   67,   59,   62,   66,   63,
       69,   65,   68,   72,   73,   74,   66,   78,   70,   75,

       71,   80,   76,   81,   84,   85,   86,   77,   82,   90,
       77,   87,   89,   91,   83,   81,   80,   78,   93,   90,
       95,   96,   78,   78,   84,   82,   92,   82,   97,   87,
       89,   85,   86,   94,   96,   98,  101,   92,   99,   91,
       95,  100,   93,  101,   94,  103,   97,  102,  104,  105,
      107,  106,  109,  103,   94,   98,   99,   97,  106,  104,
      100,  108,  109,  110,   99,  111,  102,  113,  105,  108,
      112,  121,  107,  127,  116,  126,  108,  128,  110,  129,
      130,  112,  131,  111,  116,  132,  126,  133,  127,  134,
      129,  135,  136,  113,  138,  121,  139,  140,  141,  130,

      134,  144,  131,  136,  145,  116,  128,  143,  147,  146,
      132,  133,  144,  148,  139,  145,  140,  135,  149,  138,
      146,  150,  143,  152,  153,  141,  155,  156,  147,  149,
      146,  157,  158,  159,  160,  162,  150,  161,  164,  148,
      163,  165,  157,  158,  155,  166,  161,  171,  174,  173,
      152,  153,  164,  163,  168,  170,  176,  159,  156,  165,
      160,  175,  177,  162,  178,  168,  170,  173,  174,  179,
      166,  171,  175,  177,  180,  181,  176,  182,  183,  184,
      185,  180,  334,  186,  190,  178,  188,  191,  187,  192,
      179,  194,  193,  184,  195,  181,  197,  188,  183,  190,

      198,  200,  183,  193,  182,  201,  185,  186,  187,  195,
      202,  203,  204,  191,  192,  209,  211,  194,  210,  218,
      214,  198,  197,  200,  215,  201,  219,  217,  220,  221,
      218,  226,  229,  232,  202,  203,  204,  219,  222,  220,
      211,  209,  217,  210,  214,  224,  222,  227,  215,  226,
      230,  233,  234,  235,  224,  221,  236,  229,  227,  238,
      232,  241,  243,  244,  247,  248,  235,  236,  249,  250,
      238,  233,  241,  243,  251,  230,  248,  253,  234,  255,
      259,  256,  262,  263,  247,  267,  268,  259,  249,  244,
      253,  264,  267,  263,  250,  269,  271,  272,  273,  275,

      277,  279,  282,  251,  272,  255,  256,  280,  262,  286,
      275,  264,  268,  269,  284,  289,  290,  291,  273,  279,
      292,  294,  271,  284,  286,  277,  289,  280,  282,  293,
      294,  297,  291,  298,  290,  292,  293,  299,  297,  300,
      305,  302,  298,  306,  307,  310,  309,  299,  302,  300,
      311,  312,  313,  307,  314,  317,  320,  321,  315,  319,
      322,  326,  325,  306,  328,  310,  305,  309,  312,  315,
      311,  313,  319,  322,  323,  327,  326,  321,  333,  328,
      314,  317,  320,  323,  325,  327,  335,  337,  332,  333,
      339,  340,  331,  330,  329,  324,  318,  316,  308,  304,

      303,  301,  296,  295,  288,  287,  285,  335,  337,  283,
      339,  340,  344,  344,  281,  344,  344,  345,  345,  345,
      345,  345,  347,  347,  348,  278,  348,  348,  348,  349,
      349,  276,  274,  270,  266,  265,  261,  260,  258,  257,
      254,  252,  246,  245,  242,  240,  239,  237,  231,  228,
      225,  223,  216,  213,  212,  208,  207,  206,  205,  199,
      196,  189,  172,  169,  167,  154,  151,  142,  137,  125,
      124,  123,  122,  120,  119,  118,  117,   88,   79,   64,
       60,   56,   55,   54,   45,   31,   20,   15,   14,    9,
        5,  343,  343,  343,  343,  343,  343,  343,  343,  343,

      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "sql_parser.l"
#define INITIAL 0
/*
 *This is the lexer file which defines tokens
 *
 *
 */
/*******************************************************************************
 * options section 
 ******************************************************************************/
/* set lexer options */
/* includes */
#line 17 "sql_parser.l"
#include "common.h"
#include "log/logger.h"
#include "mem_manager/mem_mgr.h"
#include "model/expression/expression.h"
#include "model/list/list.h"
#include "model/node/nodetype.h"
#include "parser/parse_internal.h"
#include "sql_parser.tab.h"

#undef free

#define TOKSELF() { \
	TRACE_LOG("Lexed TOKENSELF <%c> with VALUE <%c>", yytext[0], yytext[0]); \
	yylval.stringVal = strdup(yytext); \
	return yytext[0]; \
	}
#define TOK(name) { \
	TRACE_LOG("Lexed TOKEN <%s> with VALUE <%s>", #name, yytext); \
 	yylval.stringVal = strdup(yytext); \
 	return name; \
 	}
#define UPCASE_TOK(name) { \
	TRACE_LOG("Lexed TOKEN <%s> with VALUE <%s>", #name, yytext); \
	char *result = strdup(yytext); \
	yylval.stringVal = result; \
	for(; *result != '\0'; (*(result) = toupper(*result)), result++); \
	return name; \
	}
#define TOKSAVE(name,field,function) { \
	TRACE_LOG("Lexed TOKEN <%s> of TYPE <%s>",  #name, #field); \
	yylval.field = function(yytext); \
	return name; \
	}
/********************************************************************
 * lexer states 
 */
#define SQL 1

/********************************************************************
 * predefined regular expressions 
 */
/* whitespace */
/* numbers */
/* names (e.g., tables, attributes) */
/* operators */
/* comparisonOps	['!'|'<'|'>'|'=']{1,2} */ 
/*shiftsOps		["<<"|">>"] */
/*******************************************************************************
 * Token definitions and actions 
 ******************************************************************************/
#line 767 "sql_parser.lex.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 93 "sql_parser.l"


	/* ignore all whitespace */
#line 922 "sql_parser.lex.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 344 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 692 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 96 "sql_parser.l"
{ TRACE_LOG("Lexed whitespace <%s>", yytext); /* ignore it */ }
	YY_BREAK
/* literal keyword tokens */
case 2:
YY_RULE_SETUP
#line 99 "sql_parser.l"
TOK(SELECT)
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 100 "sql_parser.l"
TOK(INSERT)
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 101 "sql_parser.l"
TOK(UPDATE)
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 102 "sql_parser.l"
TOK(DELETE)
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 103 "sql_parser.l"
TOK(SET)
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 104 "sql_parser.l"
TOK(PROVENANCE)
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 105 "sql_parser.l"
TOK(OF)
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 106 "sql_parser.l"
TOK(FROM)
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 107 "sql_parser.l"
TOK(AS)
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 108 "sql_parser.l"
TOK(WHERE)
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 109 "sql_parser.l"
TOK(DISTINCT)
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 110 "sql_parser.l"
TOK(ON)
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 111 "sql_parser.l"
TOK(STARALL)
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 112 "sql_parser.l"
TOK(ALL)
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 113 "sql_parser.l"
TOK(AND)
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 114 "sql_parser.l"
TOK(OR)
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 115 "sql_parser.l"
TOK(AMMSC)
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 116 "sql_parser.l"
TOK(AMMSC)
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 117 "sql_parser.l"
TOK(AMMSC)
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 118 "sql_parser.l"
TOK(AMMSC)
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 119 "sql_parser.l"
TOK(AMMSC)
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 120 "sql_parser.l"
TOK(ANY)
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 121 "sql_parser.l"
TOK(SOME)
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 122 "sql_parser.l"
TOK(BETWEEN)
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 123 "sql_parser.l"
TOK(BY)
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 124 "sql_parser.l"
TOK(UPDATE)
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 125 "sql_parser.l"
TOK(DELETE)
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 126 "sql_parser.l"
TOK(IS)
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 127 "sql_parser.l"
TOK(NULLVAL)
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 128 "sql_parser.l"
TOK(UNION)
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 129 "sql_parser.l"
TOK(INTERSECT)
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 130 "sql_parser.l"
TOK(MINUS)
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 131 "sql_parser.l"
TOK(JOIN)
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 132 "sql_parser.l"
TOK(LEFT)
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 133 "sql_parser.l"
TOK(RIGHT)
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 134 "sql_parser.l"
TOK(OUTER)
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 135 "sql_parser.l"
TOK(INNER)
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 136 "sql_parser.l"
TOK(NATURAL)
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 137 "sql_parser.l"
TOK(USING)
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 138 "sql_parser.l"
TOK(CROSS)
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 139 "sql_parser.l"
TOK(INTO)
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 140 "sql_parser.l"
TOK(VALUES)
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 141 "sql_parser.l"
TOK(IN)
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 142 "sql_parser.l"
TOK(EXISTS)
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 143 "sql_parser.l"
TOK(LIKE)
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 144 "sql_parser.l"
TOK(NOT)
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 145 "sql_parser.l"
TOK(GROUP)
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 146 "sql_parser.l"
TOK(HAVING)
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 147 "sql_parser.l"
TOK(LIMIT)
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 148 "sql_parser.l"
TOK(ORDER)
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 149 "sql_parser.l"
TOK(BEGIN_TRANS)
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 150 "sql_parser.l"
TOK(COMMIT_TRANS)
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 151 "sql_parser.l"
TOK(ROLLBACK_TRANS)
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 152 "sql_parser.l"
TOK(ROLLBACK_TRANS)
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 153 "sql_parser.l"
TOK(BASERELATION)
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 154 "sql_parser.l"
TOK(SCN)
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 155 "sql_parser.l"
TOK(TIMESTAMP)
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 156 "sql_parser.l"
TOK(TYPE)
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 157 "sql_parser.l"
TOK(TRANSACTION)
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 158 "sql_parser.l"
TOK(WITH)
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 159 "sql_parser.l"
TOK(HAS)
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 160 "sql_parser.l"
TOK(CASE)
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 161 "sql_parser.l"
TOK(WHEN)
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 162 "sql_parser.l"
TOK(THEN)
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 163 "sql_parser.l"
TOK(END)
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 164 "sql_parser.l"
TOK(ELSE)
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 165 "sql_parser.l"
TOK(OVER_TOK)
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 166 "sql_parser.l"
TOK(PARTITION)
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 167 "sql_parser.l"
TOK(ROWS)
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 168 "sql_parser.l"
TOK(RANGE)
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 169 "sql_parser.l"
TOK(UNBOUNDED)
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 170 "sql_parser.l"
TOK(PRECEDING)
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 171 "sql_parser.l"
TOK(CURRENT)
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 172 "sql_parser.l"
TOK(ROW)
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 173 "sql_parser.l"
TOK(FOLLOWING)
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 174 "sql_parser.l"
TOK(TABLE)
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 175 "sql_parser.l"
TOK(ONLY)
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 176 "sql_parser.l"
TOK(UPDATED)
	YY_BREAK
/* names */
case 80:
YY_RULE_SETUP
#line 179 "sql_parser.l"
UPCASE_TOK(identifier)
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 180 "sql_parser.l"
{ 		
		yylval.stringVal = MALLOC(strlen(yytext) - 1);
		memcpy(yylval.stringVal, yytext + 1, strlen(yytext) - 2);
		yylval.stringVal[strlen(yytext) -1] = '\0';
		TRACE_LOG("Lexed TOKEN <quotedIdentifier> with VALUE <%s>", yytext);
		return identifier;
	}	
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 188 "sql_parser.l"
{
		yylval.stringVal = MALLOC(strlen(yytext));
		memcpy(yylval.stringVal, yytext + 1, strlen(yytext) - 1);
		yylval.stringVal[strlen(yytext) - 1] = '\0';
		TRACE_LOG("Lexed TOKEN <parameter> with VALUE <:%s>", yytext);
		return parameter;
	}
	YY_BREAK
/* punctuation */
case 83:
YY_RULE_SETUP
#line 197 "sql_parser.l"
TOKSELF()
	YY_BREAK
/* operators */
case 84:
YY_RULE_SETUP
#line 200 "sql_parser.l"
TOK(comparisonOps)
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 201 "sql_parser.l"
TOKSELF()
	YY_BREAK
/* numbers */
case 86:
YY_RULE_SETUP
#line 206 "sql_parser.l"
TOKSAVE(intConst,intVal,atoi)
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 207 "sql_parser.l"
TOKSAVE(floatConst,floatVal,atof)
	YY_BREAK
/* strings */
case 88:
YY_RULE_SETUP
#line 210 "sql_parser.l"
{
		yylval.stringVal = MALLOC(strlen(yytext) - 1);
		memcpy(yylval.stringVal, yytext + 1, strlen(yytext) - 2);
		yylval.stringVal[strlen(yytext) - 2] = '\0';
		TRACE_LOG("Lexed TOKEN <stringConst> with VALUE <%s>", yytext);
		return stringConst;
	}
	YY_BREAK
case 89:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 219 "sql_parser.l"
{yyerror("Unterminated string"); }
	YY_BREAK
/* failure - no token matched */
case 90:
YY_RULE_SETUP
#line 222 "sql_parser.l"
{ yyerror("Unknown symbol"); }	/* random non-SQL text */
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 224 "sql_parser.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1496 "sql_parser.lex.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(SQL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 344 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 344 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 343);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 224 "sql_parser.l"


/*******************************************************************************
 * Literal C code to include
 ******************************************************************************/

/* use logging framework in the future */
void yyerror(char *s)
{
	ERROR_LOG("%s at %s\n", s, yytext);
}

void setupStringInput(char *input)
{
	yy_scan_string(input);
}
