#line 2 "sql_parser.lex.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 67
#define YY_END_OF_BUFFER 68
static yyconst short int yy_acclist[361] =
    {   0,
       68,   66,   67,    1,   66,   67,    1,   67,   61,   66,
       67,   66,   67,   61,   66,   67,   66,   67,   59,   66,
       67,   61,   66,   67,   59,   66,   67,   62,   63,   66,
       67,   60,   66,   67,   60,   66,   67,   60,   66,   67,
       57,   66,   67,   57,   66,   67,   57,   66,   67,   57,
       66,   67,   57,   66,   67,   57,   66,   67,   57,   66,
       67,   57,   66,   67,   57,   66,   67,   57,   66,   67,
       57,   66,   67,   57,   66,   67,   57,   66,   67,   57,
       66,   67,   57,   66,   67,   57,   66,   67,   57,   66,
       67,   57,   66,   67,   57,   66,   67,   57,   66,   67,

       57,   66,   67,    1,   60,   65,   64,    1,   63,   63,
       62,   63,   57,   57,   57,   57,   10,   57,   57,   57,
       57,   26,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   44,   57,   29,   57,   57,   57,   57,   57,   57,
       57,   57,   57,    8,   57,   13,   57,   17,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   58,    1,   63,   63,   57,   15,   57,   16,
       57,   23,   57,   18,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   20,   57,   19,   57,   57,   47,

       57,   57,   57,   57,   57,   57,   57,   57,    6,   57,
       57,   57,   21,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,    9,
       57,   57,   57,   57,   57,   57,   42,   57,   34,   57,
       35,   57,   46,   57,   57,   57,   57,   30,   57,   57,
       57,   57,   57,   57,   57,   24,   57,   57,   57,   57,
       57,   57,   57,   55,   57,   57,   52,   57,   57,   57,
       22,   57,   41,   57,   57,   57,   57,   48,   57,   57,
       38,   57,   57,   57,   50,   57,   33,   57,   57,   51,
       57,   37,   57,   57,   36,   57,   57,   57,   57,   31,

       57,   57,   40,   57,   57,   11,   57,   57,   57,   53,
       57,    5,   28,   57,   57,   45,   57,   49,   57,    3,
       57,   57,   57,   57,   57,    2,   57,   14,   57,    4,
       27,   57,   43,   57,   57,   25,   57,   57,   57,   39,
       57,   57,   57,   57,   12,   57,   57,   57,   54,   57,
       57,   32,   57,   57,   57,    7,   57,   57,   56,   57
    } ;

static yyconst short int yy_accept[249] =
    {   0,
        1,    1,    1,    1,    1,    2,    4,    7,    9,   12,
       14,   17,   19,   22,   25,   28,   32,   35,   38,   41,
       44,   47,   50,   53,   56,   59,   62,   65,   68,   71,
       74,   77,   80,   83,   86,   89,   92,   95,   98,  101,
      104,  105,  106,  106,  106,  107,  108,  109,  110,  111,
      113,  113,  114,  114,  115,  116,  117,  119,  120,  121,
      122,  124,  125,  126,  127,  128,  129,  130,  131,  132,
      134,  136,  137,  138,  139,  140,  141,  142,  143,  144,
      146,  148,  150,  151,  152,  153,  154,  155,  156,  157,
      158,  159,  160,  161,  162,  163,  164,  165,  166,  166,

      167,  168,  170,  172,  174,  176,  177,  178,  179,  180,
      181,  182,  183,  184,  185,  186,  187,  188,  189,  190,
      191,  192,  193,  194,  195,  197,  199,  200,  202,  203,
      204,  205,  206,  207,  208,  209,  211,  212,  213,  215,
      216,  217,  218,  219,  220,  221,  222,  223,  224,  225,
      226,  227,  228,  229,  230,  232,  233,  234,  235,  236,
      237,  239,  241,  243,  245,  246,  247,  248,  250,  251,
      252,  253,  254,  255,  256,  258,  259,  260,  261,  262,
      263,  264,  266,  267,  269,  270,  271,  273,  275,  276,
      277,  278,  280,  281,  283,  284,  285,  287,  289,  290,

      292,  294,  295,  297,  298,  299,  300,  302,  303,  305,
      306,  308,  309,  310,  312,  315,  316,  318,  320,  322,
      323,  324,  325,  326,  328,  330,  333,  335,  336,  338,
      339,  340,  342,  343,  344,  345,  347,  348,  349,  351,
      352,  354,  355,  356,  358,  359,  361,  361
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       10,    8,   11,   10,   12,   13,    8,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    1,   10,   15,
       16,   17,   18,    1,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   35,
        1,    1,    1,    8,   18,    1,   35,   35,   35,   35,

       44,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,    1,    8,    1,    8,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[45] =
    {   0,
        1,    1,    2,    2,    1,    3,    4,    1,    1,    1,
        1,    1,    4,    4,    1,    1,    1,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4
    } ;

static yyconst short int yy_base[252] =
    {   0,
        0,    0,    0,    0,  497,  498,   43,   46,  480,    0,
      498,   48,  498,  483,  480,   39,   38,  498,  477,   45,
       47,   43,   46,   50,   48,   51,   55,   54,   65,  479,
       76,   75,   82,   80,   84,   95,   94,   92,   87,   83,
      132,  498,  485,  122,  498,  498,    0,  100,  116,  124,
       99,  477,  476,  128,  127,  129,  475,  130,  132,  133,
      474,  135,  137,  143,  139,  136,  146,  149,  140,  151,
      473,  154,  141,  162,  164,  165,  171,  172,  173,  472,
      471,   58,  174,  181,  177,  183,  185,  186,  182,  187,
      192,   59,  194,  195,  203,  498,    0,  197,  469,  468,

      191,  468,  467,  466,  465,  209,  211,  215,  216,  217,
      218,  220,  221,  223,  222,  224,  227,  229,  235,  238,
      232,  231,  244,  249,  464,  226,  233,  463,  253,  255,
      257,  237,  260,  261,  262,  462,  266,  268,  461,  269,
      271,  274,  275,  279,  280,  281,  284,  282,  283,  285,
      287,  288,  286,  290,  460,  295,  298,  296,  299,  306,
      459,  458,  457,  456,  307,  294,  308,  455,  312,  314,
      320,  309,  321,  325,  454,  323,  324,  326,  327,  336,
      338,  453,  342,  452,  344,  341,  451,  450,  345,  349,
      347,  449,  350,  448,  353,  356,  447,  446,  357,  445,

      444,  358,  443,  359,  360,  364,  442,  369,  441,  367,
      440,  370,  373,  439,  436,  374,  429,  422,  421,  376,
      372,  384,  375,  420,  419,  417,  414,  388,  412,  393,
      395,  410,  396,  397,  398,  409,  399,  400,  406,  402,
      404,  401,  405,  361,  407,  179,  498,  439,  443,  114,
      447
    } ;

static yyconst short int yy_def[252] =
    {   0,
      247,    1,    1,    1,  247,  247,  247,  247,  247,  248,
      247,  249,  247,  247,  247,  247,  247,  247,  247,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      247,  247,  248,  249,  247,  247,  251,  247,  247,  247,
      247,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  247,  251,  247,  247,  247,

      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,

      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,    0,  247,  247,  247,
      247
    } ;

static yyconst short int yy_nxt[543] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   11,   12,   13,
       11,   14,   15,   16,   17,   18,   19,    6,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   30,   36,   37,   30,   38,   39,
       40,   30,   30,   30,   41,   41,   41,   41,   41,   41,
       45,   49,   50,   42,   42,   53,   46,   53,   53,   53,
       53,   51,   53,   53,   54,   59,   53,   53,   64,   60,
       53,   53,   65,   69,   55,   62,   56,   53,   63,  130,
      141,   57,   51,   67,   58,   70,   68,   53,   53,   61,
       71,   66,   53,   75,   53,   53,   53,   72,   73,   53,

       77,   76,   74,   80,   53,   94,   53,   53,   95,   99,
       99,   81,  100,   48,   78,   82,   87,   52,   83,   84,
       79,   85,   51,   91,   45,   92,   88,   86,   93,   98,
       46,   89,   90,   41,   41,   41,   49,   50,   51,   53,
       53,   53,   53,   51,   53,   53,   51,   53,   53,   53,
      103,   53,   53,   53,  105,   53,  102,  107,   53,   51,
      101,   53,  114,   53,  122,  109,   53,   51,  106,  111,
      108,  104,  112,  110,   53,  113,   53,   53,  115,  117,
      121,  116,  118,   53,   53,   53,   53,  119,  120,   53,
      123,   53,  124,   53,   53,   53,  126,   53,   53,   53,

      138,  133,  129,   53,   53,  125,   53,   53,  127,  128,
       98,  131,  134,  132,  135,   53,  137,  139,  140,   51,
      142,   53,  136,   53,  143,  144,  145,   53,   53,   53,
       53,  146,   53,   53,   53,   53,   53,  147,   53,   53,
       51,   53,  152,   53,   53,   53,  149,   53,  150,   53,
       53,  158,  155,  157,  151,  148,   53,  159,  153,  154,
      160,   53,  156,  162,  166,   53,  164,   53,  163,   53,
      161,  167,   53,   53,   53,  165,  171,  169,   53,  170,
       53,   53,  168,   53,  174,  172,   53,   53,  175,  178,
      173,   53,   53,   53,   53,   53,   53,   53,   53,   53,

       53,  177,   53,  176,  185,  179,   53,   53,   53,  186,
       53,   53,  190,  180,  181,  184,  183,  182,   53,   53,
       53,   53,  187,  188,   53,  189,   53,  191,  192,  193,
      198,  194,   53,   53,  195,   53,   53,   53,   53,   53,
      204,  196,  202,  199,  197,  205,  203,  200,   53,  201,
       53,  209,  206,   53,   53,  207,   53,   53,  210,   53,
      211,   53,   53,  208,  212,   53,  213,  215,   53,   53,
       53,   53,   53,   53,  218,  221,   53,  223,  214,   53,
      216,   53,   53,  217,   53,   53,   53,   53,   53,  222,
      219,  226,  220,  225,  230,  234,   53,  224,  231,  228,

       53,  232,  233,  227,  229,   53,  235,   53,   53,   53,
       53,   53,   53,   53,   53,  237,   53,   53,   53,   53,
      242,   53,   53,  244,   53,  239,   53,  238,  243,   53,
      236,   53,   53,   53,   53,  240,  241,  245,  246,   43,
       43,   53,   43,   44,   44,   44,   44,   97,   53,   97,
       97,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,  100,  100,   53,   53,   53,   53,   53,  247,   53,
       96,   53,   42,   48,   47,   42,  247,    5,  247,  247,

      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247
    } ;

static yyconst short int yy_chk[543] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    7,    7,    7,    8,    8,    8,
       12,   16,   16,   17,   17,   22,   12,   20,   23,   21,
       25,   16,   24,   26,   20,   21,   28,   27,   23,   21,
       82,   92,   23,   27,   20,   22,   20,   29,   22,   82,
       92,   20,   16,   25,   20,   28,   26,   32,   31,   21,
       28,   24,   34,   32,   33,   40,   35,   29,   31,   39,

       33,   32,   31,   34,   38,   39,   37,   36,   40,   51,
       51,   34,   51,   48,   33,   34,   37,  250,   34,   35,
       33,   36,   48,   38,   44,   38,   37,   36,   38,   49,
       44,   37,   37,   41,   41,   41,   50,   50,   49,   55,
       54,   56,   58,   48,   59,   60,   50,   62,   66,   63,
       56,   65,   69,   73,   58,   64,   55,   60,   67,   49,
       54,   68,   66,   70,   73,   62,   72,   50,   59,   63,
       60,   56,   64,   62,   74,   65,   75,   76,   67,   69,
       72,   68,   70,   77,   78,   79,   83,   70,   70,   85,
       74,  246,   74,   84,   89,   86,   76,   87,   88,   90,

       89,   85,   79,  101,   91,   75,   93,   94,   77,   78,
       98,   83,   86,   84,   87,   95,   88,   90,   91,   98,
       93,  106,   87,  107,   94,   95,  101,  108,  109,  110,
      111,  106,  112,  113,  115,  114,  116,  107,  126,  117,
       98,  118,  112,  122,  121,  127,  109,  119,  110,  132,
      120,  118,  115,  117,  111,  108,  123,  119,  113,  114,
      120,  124,  116,  121,  126,  129,  123,  130,  122,  131,
      120,  127,  133,  134,  135,  124,  132,  130,  137,  131,
      138,  140,  129,  141,  135,  133,  142,  143,  137,  141,
      134,  144,  145,  146,  148,  149,  147,  150,  153,  151,

      152,  140,  154,  138,  148,  142,  166,  156,  158,  149,
      157,  159,  153,  143,  144,  147,  146,  145,  160,  165,
      167,  172,  150,  151,  169,  152,  170,  154,  156,  157,
      166,  158,  171,  173,  159,  176,  177,  174,  178,  179,
      173,  160,  171,  167,  165,  174,  172,  169,  180,  170,
      181,  179,  176,  186,  183,  177,  185,  189,  180,  191,
      181,  190,  193,  178,  183,  195,  185,  189,  196,  199,
      202,  204,  205,  244,  193,  199,  206,  204,  186,  210,
      190,  208,  212,  191,  221,  213,  216,  223,  220,  202,
      195,  208,  196,  206,  216,  223,  222,  205,  220,  212,

      228,  221,  222,  210,  213,  230,  228,  231,  233,  234,
      235,  237,  238,  242,  240,  231,  241,  243,  239,  245,
      238,  236,  232,  242,  229,  234,  227,  233,  240,  226,
      230,  225,  224,  219,  218,  235,  237,  243,  245,  248,
      248,  217,  248,  249,  249,  249,  249,  251,  215,  251,
      251,  214,  211,  209,  207,  203,  201,  200,  198,  197,
      194,  192,  188,  187,  184,  182,  175,  168,  164,  163,
      162,  161,  155,  139,  136,  128,  125,  105,  104,  103,
      102,  100,   99,   81,   80,   71,   61,   57,   53,   52,
       43,   30,   19,   15,   14,    9,    5,  247,  247,  247,

      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "sql_parser.l"
#define INITIAL 0
/*
 *This is the lexer file which defines tokens
 *
 *
 */
/*******************************************************************************
 * options section 
 ******************************************************************************/
/* set lexer options */
/* includes */
#line 17 "sql_parser.l"
#include "common.h"
#include "log/logger.h"
#include "mem_manager/mem_mgr.h"
#include "model/expression/expression.h"
#include "model/list/list.h"
#include "model/node/nodetype.h"
#include "parser/parse_internal.h"
#include "sql_parser.tab.h"

#undef free

#define TOKSELF() { \
	TRACE_LOG("Lexed TOKENSELF <%c> with VALUE <%c>", yytext[0], yytext[0]); \
	yylval.stringVal = strdup(yytext); \
	return yytext[0]; \
	}
#define TOK(name) { \
	TRACE_LOG("Lexed TOKEN <%s> with VALUE <%s>", #name, yytext); \
 	yylval.stringVal = strdup(yytext); \
 	return name; \
 	}
#define UPCASE_TOK(name) { \
	TRACE_LOG("Lexed TOKEN <%s> with VALUE <%s>", #name, yytext); \
	char *result = strdup(yytext); \
	yylval.stringVal = result; \
	for(; *result != '\0'; (*(result) = toupper(*result)), result++); \
	return name; \
	}
#define TOKSAVE(name,field,function) { \
	TRACE_LOG("Lexed TOKEN <%s> of TYPE <%s>",  #name, #field); \
	yylval.field = function(yytext); \
	return name; \
	}
/********************************************************************
 * lexer states 
 */
#define SQL 1

/********************************************************************
 * predefined regular expressions 
 */
/* whitespace */
/* numbers */
/* names (e.g., tables, attributes) */
/* operators */
/* comparisonOps	['!'|'<'|'>'|'=']{1,2} */ 
/*shiftsOps		["<<"|">>"] */
/*******************************************************************************
 * Token definitions and actions 
 ******************************************************************************/
#line 680 "sql_parser.lex.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 92 "sql_parser.l"


	/* ignore all whitespace */
#line 835 "sql_parser.lex.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 248 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 498 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 95 "sql_parser.l"
{ TRACE_LOG("Lexed whitespace <%s>", yytext); /* ignore it */ }
	YY_BREAK
/* literal keyword tokens */
case 2:
YY_RULE_SETUP
#line 98 "sql_parser.l"
TOK(SELECT)
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 99 "sql_parser.l"
TOK(INSERT)
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 100 "sql_parser.l"
TOK(UPDATE)
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 101 "sql_parser.l"
TOK(DELETE)
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 102 "sql_parser.l"
TOK(SET)
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 103 "sql_parser.l"
TOK(PROVENANCE)
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 104 "sql_parser.l"
TOK(OF)
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 105 "sql_parser.l"
TOK(FROM)
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 106 "sql_parser.l"
TOK(AS)
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 107 "sql_parser.l"
TOK(WHERE)
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 108 "sql_parser.l"
TOK(DISTINCT)
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 109 "sql_parser.l"
TOK(ON)
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 110 "sql_parser.l"
TOK(STARALL)
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 111 "sql_parser.l"
TOK(ALL)
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 112 "sql_parser.l"
TOK(AND)
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 113 "sql_parser.l"
TOK(OR)
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 114 "sql_parser.l"
TOK(AMMSC)
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 115 "sql_parser.l"
TOK(AMMSC)
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 116 "sql_parser.l"
TOK(AMMSC)
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 117 "sql_parser.l"
TOK(AMMSC)
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 118 "sql_parser.l"
TOK(AMMSC)
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 119 "sql_parser.l"
TOK(ANY)
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 120 "sql_parser.l"
TOK(SOME)
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 121 "sql_parser.l"
TOK(BETWEEN)
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 122 "sql_parser.l"
TOK(BY)
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 123 "sql_parser.l"
TOK(UPDATE)
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 124 "sql_parser.l"
TOK(DELETE)
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 125 "sql_parser.l"
TOK(IS)
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 126 "sql_parser.l"
TOK(NULLVAL)
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 127 "sql_parser.l"
TOK(UNION)
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 128 "sql_parser.l"
TOK(INTERSECT)
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 129 "sql_parser.l"
TOK(MINUS)
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 130 "sql_parser.l"
TOK(JOIN)
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 131 "sql_parser.l"
TOK(LEFT)
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 132 "sql_parser.l"
TOK(RIGHT)
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 133 "sql_parser.l"
TOK(OUTER)
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 134 "sql_parser.l"
TOK(INNER)
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 135 "sql_parser.l"
TOK(NATURAL)
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 136 "sql_parser.l"
TOK(USING)
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 137 "sql_parser.l"
TOK(CROSS)
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 138 "sql_parser.l"
TOK(INTO)
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 139 "sql_parser.l"
TOK(VALUES)
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 140 "sql_parser.l"
TOK(IN)
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 141 "sql_parser.l"
TOK(EXISTS)
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 142 "sql_parser.l"
TOK(LIKE)
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 143 "sql_parser.l"
TOK(NOT)
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 144 "sql_parser.l"
TOK(GROUP)
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 145 "sql_parser.l"
TOK(HAVING)
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 146 "sql_parser.l"
TOK(LIMIT)
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 147 "sql_parser.l"
TOK(ORDER)
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 148 "sql_parser.l"
TOK(BEGIN_TRANS)
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 149 "sql_parser.l"
TOK(COMMIT_TRANS)
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 150 "sql_parser.l"
TOK(ROLLBACK_TRANS)
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 151 "sql_parser.l"
TOK(ROLLBACK_TRANS)
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 152 "sql_parser.l"
TOK(BASERELATION)
	YY_BREAK
/* names */
case 57:
YY_RULE_SETUP
#line 155 "sql_parser.l"
UPCASE_TOK(identifier)
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 156 "sql_parser.l"
{ 		
		yylval.stringVal = MALLOC(strlen(yytext) - 1);
		memcpy(yylval.stringVal, yytext + 1, strlen(yytext) - 2);
		yylval.stringVal[strlen(yytext) -1] = '\0';
		TRACE_LOG("Lexed TOKEN <quotedIdentifier> with VALUE <%s>", yytext);
		return identifier;
	}	
	YY_BREAK
/* punctuation */
case 59:
YY_RULE_SETUP
#line 165 "sql_parser.l"
TOKSELF()
	YY_BREAK
/* operators */
case 60:
YY_RULE_SETUP
#line 168 "sql_parser.l"
TOK(comparisonOps)
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 169 "sql_parser.l"
TOKSELF()
	YY_BREAK
/* numbers */
case 62:
YY_RULE_SETUP
#line 174 "sql_parser.l"
TOKSAVE(intConst,intVal,atoi)
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 175 "sql_parser.l"
TOKSAVE(floatConst,floatVal,atof)
	YY_BREAK
/* strings */
case 64:
YY_RULE_SETUP
#line 178 "sql_parser.l"
{
		yylval.stringVal = MALLOC(strlen(yytext) - 1);
		memcpy(yylval.stringVal, yytext + 1, strlen(yytext) - 2);
		yylval.stringVal[strlen(yytext) -1] = '\0';
		TRACE_LOG("Lexed TOKEN <stringConst> with VALUE <%s>", yytext);
		return stringConst;
	}
	YY_BREAK
case 65:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 187 "sql_parser.l"
{yyerror("Unterminated string"); }
	YY_BREAK
/* failure - no token matched */
case 66:
YY_RULE_SETUP
#line 190 "sql_parser.l"
{ yyerror("Unknown symbol"); }	/* random non-SQL text */
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 192 "sql_parser.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1283 "sql_parser.lex.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(SQL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 248 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 248 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 247);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 192 "sql_parser.l"


/*******************************************************************************
 * Literal C code to include
 ******************************************************************************/

/* use logging framework in the future */
void yyerror(char *s)
{
	ERROR_LOG("%s at %s\n", s, yytext);
}

void setupStringInput(char *input)
{
	yy_scan_string(input);
}
