#line 2 "sql_parser.lex.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 66
#define YY_END_OF_BUFFER 67
static yyconst short int yy_acclist[349] =
    {   0,
       67,   65,   66,    1,   65,   66,    1,   66,   60,   65,
       66,   65,   66,   60,   65,   66,   65,   66,   58,   65,
       66,   60,   65,   66,   58,   65,   66,   61,   62,   65,
       66,   59,   65,   66,   59,   65,   66,   59,   65,   66,
       56,   65,   66,   56,   65,   66,   56,   65,   66,   56,
       65,   66,   56,   65,   66,   56,   65,   66,   56,   65,
       66,   56,   65,   66,   56,   65,   66,   56,   65,   66,
       56,   65,   66,   56,   65,   66,   56,   65,   66,   56,
       65,   66,   56,   65,   66,   56,   65,   66,   56,   65,
       66,   56,   65,   66,   56,   65,   66,   56,   65,   66,

       56,   65,   66,    1,   59,   64,   63,    1,   62,   62,
       61,   62,   56,   56,   56,   56,   10,   56,   56,   56,
       26,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       44,   56,   29,   56,   56,   56,   56,   56,   56,   56,
       56,   56,    8,   56,   13,   56,   17,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   57,    1,   62,   62,   56,   15,   56,   16,   56,
       23,   56,   18,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   20,   56,   19,   56,   56,   47,   56,   56,

       56,   56,   56,   56,   56,   56,    6,   56,   56,   56,
       21,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,    9,   56,   56,   56,
       56,   56,   56,   42,   56,   34,   56,   35,   56,   46,
       56,   56,   56,   56,   30,   56,   56,   56,   56,   56,
       56,   56,   24,   56,   56,   56,   56,   56,   56,   56,
       55,   56,   52,   56,   56,   56,   22,   56,   41,   56,
       56,   56,   56,   48,   56,   56,   38,   56,   56,   56,
       50,   56,   33,   56,   56,   51,   56,   37,   56,   56,
       36,   56,   56,   56,   56,   31,   56,   56,   40,   56,

       56,   11,   56,   56,   53,   56,    5,   28,   56,   56,
       45,   56,   49,   56,    3,   56,   56,   56,   56,   56,
        2,   56,   14,   56,    4,   27,   56,   43,   56,   25,
       56,   56,   56,   39,   56,   56,   56,   12,   56,   56,
       56,   54,   56,   32,   56,   56,    7,   56
    } ;

static yyconst short int yy_accept[238] =
    {   0,
        1,    1,    1,    1,    1,    2,    4,    7,    9,   12,
       14,   17,   19,   22,   25,   28,   32,   35,   38,   41,
       44,   47,   50,   53,   56,   59,   62,   65,   68,   71,
       74,   77,   80,   83,   86,   89,   92,   95,   98,  101,
      104,  105,  106,  106,  106,  107,  108,  109,  110,  111,
      113,  113,  114,  114,  115,  116,  117,  119,  120,  121,
      123,  124,  125,  126,  127,  128,  129,  130,  131,  133,
      135,  136,  137,  138,  139,  140,  141,  142,  143,  145,
      147,  149,  150,  151,  152,  153,  154,  155,  156,  157,
      158,  159,  160,  161,  162,  163,  164,  165,  165,  166,

      167,  169,  171,  173,  175,  176,  177,  178,  179,  180,
      181,  182,  183,  184,  185,  186,  187,  188,  189,  190,
      191,  192,  193,  195,  197,  198,  200,  201,  202,  203,
      204,  205,  206,  207,  209,  210,  211,  213,  214,  215,
      216,  217,  218,  219,  220,  221,  222,  223,  224,  225,
      226,  227,  229,  230,  231,  232,  233,  234,  236,  238,
      240,  242,  243,  244,  245,  247,  248,  249,  250,  251,
      252,  253,  255,  256,  257,  258,  259,  260,  261,  263,
      265,  266,  267,  269,  271,  272,  273,  274,  276,  277,
      279,  280,  281,  283,  285,  286,  288,  290,  291,  293,

      294,  295,  296,  298,  299,  301,  302,  304,  305,  307,
      310,  311,  313,  315,  317,  318,  319,  320,  321,  323,
      325,  328,  330,  332,  333,  334,  336,  337,  338,  340,
      341,  342,  344,  346,  347,  349,  349
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       10,    8,   11,   10,   12,   13,    8,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    1,   10,   15,
       16,   17,   18,    1,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   35,
        1,    1,    1,    8,   18,    1,   35,   35,   35,   35,

       44,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,    1,    8,    1,    8,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[45] =
    {   0,
        1,    1,    2,    2,    1,    3,    4,    1,    1,    1,
        1,    1,    4,    4,    1,    1,    1,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4
    } ;

static yyconst short int yy_base[241] =
    {   0,
        0,    0,    0,    0,  475,  476,   43,   46,  458,    0,
      476,   48,  476,  461,  458,   39,   38,  476,  455,   45,
       43,   48,   46,   47,   51,   54,   55,   59,   65,  457,
       79,   80,   75,   87,   67,   82,   97,   84,   57,   91,
      125,  476,  463,  122,  476,  476,    0,   99,  110,  124,
      128,  455,  454,   99,  121,  128,  453,  131,  132,  452,
      133,  136,  135,  139,  140,  142,  145,  146,  147,  451,
      150,  149,  161,  153,  148,  168,  169,  170,  450,  449,
      174,  175,  176,  178,  180,  181,  184,  185,  186,  189,
      192,  195,  188,  207,  476,    0,  198,  447,  446,  210,

      446,  445,  444,  443,  211,  212,  213,  215,  214,  216,
      218,  220,  219,   66,  221,  222,  236,  239,  223,  227,
      241,  247,  442,  224,  228,  441,  245,  248,  253,  230,
      255,  256,  260,  440,  264,  265,  439,  266,  269,  271,
      267,  272,  276,  277,  279,  278,  280,  282,  283,  284,
      285,  438,  281,  294,  291,  297,  299,  437,  436,  435,
      434,  287,  300,  303,  433,  304,  307,  309,  311,  316,
       50,  432,  315,  318,  317,  321,  325,  328,  431,  430,
      329,  331,  429,  428,  334,  340,  341,  427,  343,  426,
      345,  347,  425,  424,  346,  423,  422,  348,  421,  351,

      349,  358,  420,  350,  419,  353,  416,  354,  409,  405,
      361,  404,  403,  402,  362,  363,  376,  378,  401,  400,
      399,  397,  396,  364,  379,  395,  366,  368,  394,  381,
      383,  393,  392,  388,  390,  476,  419,  423,   97,  427
    } ;

static yyconst short int yy_def[241] =
    {   0,
      236,    1,    1,    1,  236,  236,  236,  236,  236,  237,
      236,  238,  236,  236,  236,  236,  236,  236,  236,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      236,  236,  237,  238,  236,  236,  240,  236,  236,  236,
      236,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  236,  240,  236,  236,  236,  239,

      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,

      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,    0,  236,  236,  236,  236
    } ;

static yyconst short int yy_nxt[521] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   11,   12,   13,
       11,   14,   15,   16,   17,   18,   19,    6,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   30,   36,   37,   30,   38,   39,
       40,   30,   30,   30,   41,   41,   41,   41,   41,   41,
       45,   49,   50,   42,   42,   53,   46,   53,   53,   53,
       53,   51,   53,   53,   54,   59,   53,   53,   63,   53,
      201,   53,   64,   68,   55,   93,   56,   53,   53,   53,
       61,   57,   51,   62,   58,   60,   66,   53,   65,   67,
       69,   53,   53,   76,   53,   70,   53,   71,   74,   53,

       52,   72,   83,   53,  153,   73,   75,   77,   84,   53,
       79,   53,   48,   78,   85,   90,   94,   91,   80,   86,
       92,   51,   81,   97,   45,   82,   41,   41,   41,   87,
       46,  100,   51,   53,   88,   89,   49,   50,   98,   98,
       53,   99,   51,   53,   53,   53,   51,   53,   53,  102,
      101,   53,   53,   51,   53,  104,  105,   53,   53,   53,
       53,   53,   53,  107,  110,   53,  112,   51,  109,  106,
      103,  108,  120,   53,  113,  111,  119,  114,  116,  124,
       53,   53,   53,  117,  118,  115,   53,   53,   53,  121,
       53,  122,   53,   53,  123,  128,   53,   53,   53,  127,

       53,   53,  131,  136,   53,  125,  126,   53,  130,  132,
      133,   97,  129,  139,  135,  138,  137,  141,  134,   53,
       51,  140,   53,   53,   53,   53,   53,   53,   53,  142,
       53,   53,   53,   53,   53,   53,   53,  144,  149,   53,
       53,   51,   53,  146,  155,  143,  147,  154,   53,  152,
      148,   53,  145,   53,  159,  150,  151,   53,  156,   53,
       53,  157,  163,  161,  160,   53,  164,   53,   53,  168,
      166,  158,   53,  162,  165,  167,   53,   53,   53,   53,
      169,   53,  171,   53,   53,  170,  172,  175,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,  174,   53,

      173,  181,  176,   53,  182,  177,   53,  178,  180,   53,
      186,   53,   53,  179,  188,   53,   53,  183,  184,   53,
      185,   53,  187,   53,  193,  189,  190,   53,   53,   53,
       53,  198,  191,   53,  192,  200,  194,   53,  195,  196,
       53,   53,  197,   53,  202,  205,   53,  206,  199,  203,
      207,  208,   53,   53,  204,   53,  210,   53,   53,   53,
       53,   53,   53,   53,  216,   53,   53,  213,  209,  218,
       53,  211,  221,   53,   53,   53,   53,  212,   53,  217,
       53,  224,  214,  215,  225,  223,  219,  220,   53,  222,
       53,   53,  226,   53,  227,   53,  232,  231,  228,  230,

       53,  229,   53,  234,   53,   53,   53,   53,   53,   53,
      235,   53,   53,   53,   53,   53,   53,   53,  233,   43,
       43,   53,   43,   44,   44,   44,   44,   96,   53,   96,
       96,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   99,
       99,   53,   53,   53,   53,   53,  236,   53,   95,   53,
       42,   48,   47,   42,  236,    5,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,

      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236
    } ;

static yyconst short int yy_chk[521] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    7,    7,    7,    8,    8,    8,
       12,   16,   16,   17,   17,   21,   12,   20,   23,   24,
       22,   16,  171,   25,   20,   21,   26,   27,   23,   39,
      171,   28,   23,   27,   20,   39,   20,   29,  114,   35,
       22,   20,   16,   22,   20,   21,   25,   33,   24,   26,
       28,   31,   32,   33,   36,   28,   38,   29,   32,   34,

      239,   31,   35,   40,  114,   31,   32,   33,   36,   37,
       34,   54,   48,   33,   36,   38,   40,   38,   34,   37,
       38,   48,   34,   49,   44,   34,   41,   41,   41,   37,
       44,   54,   49,   55,   37,   37,   50,   50,   51,   51,
       56,   51,   48,   58,   59,   61,   50,   63,   62,   56,
       55,   64,   65,   49,   66,   58,   59,   67,   68,   69,
       75,   72,   71,   61,   63,   74,   65,   50,   62,   59,
       56,   61,   72,   73,   66,   64,   71,   67,   69,   75,
       76,   77,   78,   69,   69,   68,   81,   82,   83,   73,
       84,   73,   85,   86,   74,   81,   87,   88,   89,   78,

       93,   90,   84,   88,   91,   76,   77,   92,   83,   85,
       86,   97,   82,   91,   87,   90,   89,   93,   86,   94,
       97,   92,  100,  105,  106,  107,  109,  108,  110,   94,
      111,  113,  112,  115,  116,  119,  124,  105,  110,  120,
      125,   97,  130,  107,  116,  100,  108,  115,  117,  113,
      109,  118,  106,  121,  119,  111,  112,  127,  117,  122,
      128,  118,  124,  121,  120,  129,  125,  131,  132,  130,
      128,  118,  133,  122,  127,  129,  135,  136,  138,  141,
      131,  139,  133,  140,  142,  132,  135,  139,  143,  144,
      146,  145,  147,  153,  148,  149,  150,  151,  138,  162,

      136,  145,  140,  155,  146,  141,  154,  142,  144,  156,
      150,  157,  163,  143,  153,  164,  166,  147,  148,  167,
      149,  168,  151,  169,  162,  154,  155,  173,  170,  175,
      174,  168,  156,  176,  157,  170,  163,  177,  164,  166,
      178,  181,  167,  182,  173,  176,  185,  177,  169,  174,
      178,  181,  186,  187,  175,  189,  185,  191,  195,  192,
      198,  201,  204,  200,  195,  206,  208,  189,  182,  200,
      202,  186,  204,  211,  215,  216,  224,  187,  227,  198,
      228,  211,  191,  192,  215,  208,  201,  202,  217,  206,
      218,  225,  216,  230,  217,  231,  228,  227,  218,  225,

      234,  224,  235,  231,  233,  232,  229,  226,  223,  222,
      234,  221,  220,  219,  214,  213,  212,  210,  230,  237,
      237,  209,  237,  238,  238,  238,  238,  240,  207,  240,
      240,  205,  203,  199,  197,  196,  194,  193,  190,  188,
      184,  183,  180,  179,  172,  165,  161,  160,  159,  158,
      152,  137,  134,  126,  123,  104,  103,  102,  101,   99,
       98,   80,   79,   70,   60,   57,   53,   52,   43,   30,
       19,   15,   14,    9,    5,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,

      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "sql_parser.l"
#define INITIAL 0
/*
 *This is the lexer file which defines tokens
 *
 *
 */
/*******************************************************************************
 * options section 
 ******************************************************************************/
/* set lexer options */
/* includes */
#line 17 "sql_parser.l"
#include "common.h"
#include "log/logger.h"
#include "mem_manager/mem_mgr.h"
#include "model/expression/expression.h"
#include "model/list/list.h"
#include "model/node/nodetype.h"
#include "parser/parse_internal.h"
#include "sql_parser.tab.h"

#undef free

#define TOKSELF() { \
	TRACE_LOG("Lexed TOKENSELF <%c> with VALUE <%c>", yytext[0], yytext[0]); \
	yylval.stringVal = strdup(yytext); \
	return yytext[0]; \
	}
#define TOK(name) { \
	TRACE_LOG("Lexed TOKEN <%s> with VALUE <%s>", #name, yytext); \
 	yylval.stringVal = strdup(yytext); \
 	return name; \
 	}
#define UPCASE_TOK(name) { \
	TRACE_LOG("Lexed TOKEN <%s> with VALUE <%s>", #name, yytext); \
	char *result = strdup(yytext); \
	yylval.stringVal = result; \
	for(; *result != '\0'; (*(result) = toupper(*result)), result++); \
	return name; \
	}
#define TOKSAVE(name,field,function) { \
	TRACE_LOG("Lexed TOKEN <%s> of TYPE <%s>",  #name, #field); \
	yylval.field = function(yytext); \
	return name; \
	}
/********************************************************************
 * lexer states 
 */
#define SQL 1

/********************************************************************
 * predefined regular expressions 
 */
/* whitespace */
/* numbers */
/* names (e.g., tables, attributes) */
/* operators */
/* comparisonOps	['!'|'<'|'>'|'=']{1,2} */ 
/*shiftsOps		["<<"|">>"] */
/*******************************************************************************
 * Token definitions and actions 
 ******************************************************************************/
#line 668 "sql_parser.lex.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 92 "sql_parser.l"


	/* ignore all whitespace */
#line 823 "sql_parser.lex.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 237 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 476 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 95 "sql_parser.l"
{ TRACE_LOG("Lexed whitespace <%s>", yytext); /* ignore it */ }
	YY_BREAK
/* literal keyword tokens */
case 2:
YY_RULE_SETUP
#line 98 "sql_parser.l"
TOK(SELECT)
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 99 "sql_parser.l"
TOK(INSERT)
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 100 "sql_parser.l"
TOK(UPDATE)
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 101 "sql_parser.l"
TOK(DELETE)
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 102 "sql_parser.l"
TOK(SET)
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 103 "sql_parser.l"
TOK(PROVENANCE)
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 104 "sql_parser.l"
TOK(OF)
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 105 "sql_parser.l"
TOK(FROM)
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 106 "sql_parser.l"
TOK(AS)
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 107 "sql_parser.l"
TOK(WHERE)
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 108 "sql_parser.l"
TOK(DISTINCT)
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 109 "sql_parser.l"
TOK(ON)
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 110 "sql_parser.l"
TOK(STARALL)
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 111 "sql_parser.l"
TOK(ALL)
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 112 "sql_parser.l"
TOK(AND)
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 113 "sql_parser.l"
TOK(OR)
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 114 "sql_parser.l"
TOK(AMMSC)
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 115 "sql_parser.l"
TOK(AMMSC)
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 116 "sql_parser.l"
TOK(AMMSC)
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 117 "sql_parser.l"
TOK(AMMSC)
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 118 "sql_parser.l"
TOK(AMMSC)
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 119 "sql_parser.l"
TOK(ANY)
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 120 "sql_parser.l"
TOK(SOME)
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 121 "sql_parser.l"
TOK(BETWEEN)
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 122 "sql_parser.l"
TOK(BY)
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 123 "sql_parser.l"
TOK(UPDATE)
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 124 "sql_parser.l"
TOK(DELETE)
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 125 "sql_parser.l"
TOK(IS)
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 126 "sql_parser.l"
TOK(NULLVAL)
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 127 "sql_parser.l"
TOK(UNION)
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 128 "sql_parser.l"
TOK(INTERSECT)
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 129 "sql_parser.l"
TOK(MINUS)
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 130 "sql_parser.l"
TOK(JOIN)
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 131 "sql_parser.l"
TOK(LEFT)
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 132 "sql_parser.l"
TOK(RIGHT)
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 133 "sql_parser.l"
TOK(OUTER)
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 134 "sql_parser.l"
TOK(INNER)
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 135 "sql_parser.l"
TOK(NATURAL)
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 136 "sql_parser.l"
TOK(USING)
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 137 "sql_parser.l"
TOK(CROSS)
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 138 "sql_parser.l"
TOK(INTO)
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 139 "sql_parser.l"
TOK(VALUES)
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 140 "sql_parser.l"
TOK(IN)
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 141 "sql_parser.l"
TOK(EXISTS)
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 142 "sql_parser.l"
TOK(LIKE)
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 143 "sql_parser.l"
TOK(NOT)
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 144 "sql_parser.l"
TOK(GROUP)
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 145 "sql_parser.l"
TOK(HAVING)
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 146 "sql_parser.l"
TOK(LIMIT)
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 147 "sql_parser.l"
TOK(ORDER)
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 148 "sql_parser.l"
TOK(BEGIN_TRANS)
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 149 "sql_parser.l"
TOK(COMMIT_TRANS)
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 150 "sql_parser.l"
TOK(ROLLBACK_TRANS)
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 151 "sql_parser.l"
TOK(ROLLBACK_TRANS)
	YY_BREAK
/* names */
case 56:
YY_RULE_SETUP
#line 154 "sql_parser.l"
UPCASE_TOK(identifier)
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 155 "sql_parser.l"
{ 		
		yylval.stringVal = MALLOC(strlen(yytext) - 1);
		memcpy(yylval.stringVal, yytext + 1, strlen(yytext) - 2);
		yylval.stringVal[strlen(yytext) -1] = '\0';
		TRACE_LOG("Lexed TOKEN <quotedIdentifier> with VALUE <%s>", yytext);
		return identifier;
	}	
	YY_BREAK
/* punctuation */
case 58:
YY_RULE_SETUP
#line 164 "sql_parser.l"
TOKSELF()
	YY_BREAK
/* operators */
case 59:
YY_RULE_SETUP
#line 167 "sql_parser.l"
TOK(comparisonOps)
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 168 "sql_parser.l"
TOKSELF()
	YY_BREAK
/* numbers */
case 61:
YY_RULE_SETUP
#line 173 "sql_parser.l"
TOKSAVE(intConst,intVal,atoi)
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 174 "sql_parser.l"
TOKSAVE(floatConst,floatVal,atof)
	YY_BREAK
/* strings */
case 63:
YY_RULE_SETUP
#line 177 "sql_parser.l"
{
		yylval.stringVal = MALLOC(strlen(yytext) - 1);
		memcpy(yylval.stringVal, yytext + 1, strlen(yytext) - 2);
		yylval.stringVal[strlen(yytext) -1] = '\0';
		TRACE_LOG("Lexed TOKEN <stringConst> with VALUE <%s>", yytext);
		return stringConst;
	}
	YY_BREAK
case 64:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 186 "sql_parser.l"
{yyerror("Unterminated string"); }
	YY_BREAK
/* failure - no token matched */
case 65:
YY_RULE_SETUP
#line 189 "sql_parser.l"
{ yyerror("Unknown symbol"); }	/* random non-SQL text */
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 191 "sql_parser.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1266 "sql_parser.lex.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(SQL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 237 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 237 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 236);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 191 "sql_parser.l"


/*******************************************************************************
 * Literal C code to include
 ******************************************************************************/

/* use logging framework in the future */
void yyerror(char *s)
{
	ERROR_LOG("%s at %s\n", s, yytext);
}

void setupStringInput(char *input)
{
	yy_scan_string(input);
}
