/*
 *------------------------------------------------------------------------------
 *
 * sql_serializer_nautilus.h - SQL serializer that generates a Nautilus DB plan in the systems task language.
 *
 *     Take a plan that was generated by the Postgres JSON to query operator model translator and generate a task description understood by NautilusDB for it.
 *
 *        AUTHOR: lord_pretzel
 *        DATE: 2019-08-27
 *        SUBDIR: include/sql_serializer/
 *
 *-----------------------------------------------------------------------------
 */

#ifndef _SQL_SERIALIZER_NAUTILUS_H_
#define _SQL_SERIALIZER_NAUTILUS_H_

#include "model/node/nodetype.h"
#include "model/query_operator/query_operator.h"

extern char *serializeOperatorModelNautilus(Node *q);
extern char *serializeQueryNautilus(QueryOperator *q);
extern char *quoteIdentifierNautilus(char *ident);

#endif /* _SQL_SERIALIZER_NAUTILUS_H_ */
