pipeline {
    agent {
		  dockerfile {
		  		 dir 'jenkins/Docker/AllBackends'
				 reuseNode true
				 args '--user root'
		  }
	}
    stages {
		stage('build') {
		    steps {
				sh 'make -f Makefile.maintainer'
				sh './configure --with-oci-headers=/opt/oracle/instantclient/sdk/include/ --with-oci-lib=/opt/oracle/instantclient'
				sh 'make'
				sh 'make install'
			}
		}
		stage('dist-and-distcheck') {
			steps {
				sh 'make dist'
				sh 'make distcheck'
			}
		}
		stage('c-tests') {
			steps {
				sh 'pushd test && make check && popd'
			}
		}
    }
}
